// Generated by node tools/stamp-snake-dev.cjs; revision is Git HEAD at generation, + means edited sources.
export const DEV_BUILD=Object.freeze({
  "revision": "fcfbde6",
  "sourceRevision": "fcfbde685be0e513eca2bfa90b4adeab4322405c",
  "uncommittedSources": false,
  "fingerprint": "6b7e9dd7378c",
  "expectedVfx": "vfx-b2-c426cfb"
});
