// Generated by node tools/stamp-snake-dev.cjs; revision is Git HEAD at generation, + means edited sources.
export const DEV_BUILD=Object.freeze({
  "revision": "c426cfb+",
  "sourceRevision": "c426cfb0ad82b84f8ff288616d709523ba0b220d",
  "uncommittedSources": true,
  "fingerprint": "d1355eb212cf",
  "expectedVfx": "vfx-b2-c426cfb"
});
