import {PRESETS,validateProfile,targetSpeed,profileCadence} from './config.js';
import {labSession} from './session.js';
import {cabinetSize} from '../forest-training/renderer.js';
import {RibbonSprites} from '../forest-training/ribbon-sprites.js';
const frame=document.querySelector('#training'),status=document.querySelector('#lab-status'),fields=document.querySelector('#fields');
const labels={startSpeed:'Start speed · cells/s',maxSpeed:'Max base speed · cells/s',acceleration:'Acceleration · cells/s per second',grace:'Calm start · seconds',foodMin:'Food preferred min · Manhattan cells',foodMax:'Food preferred max · Manhattan cells',positiveInterval:'Positive interval · seconds',negativeInterval:'Negative interval · seconds',portalFirst:'First portal window · seconds',portalInterval:'Portal window interval · seconds',portalWindow:'Portal visible window · seconds',portalCooldown:'Portal cooldown · seconds',comboTimeout:'Combo timeout · seconds',comboStep:'Combo reward step'};
for(const [key,label] of Object.entries(labels)){const l=document.createElement('label');l.textContent=label;const n=document.createElement('input');n.id='cfg-'+key;n.type='number';n.step=['startSpeed','maxSpeed','acceleration','comboStep'].includes(key)?'0.001':'1';l.append(n);fields.append(l);}
let profile=PRESETS.B,game=null,current=null,queued=false;const history=[];
const motionToggle=document.querySelector('#motion-toggle');
let motionMode=0,originalSprites=null,ribbonSprites=null;
const motionLabels=['SMOOTH V4','SMOOTH V2','GRID SNAP'];
const proofWarning='SMOOTH V4 — DEV integration; awaiting human play review.';
motionToggle.textContent=motionLabels[motionMode];
motionToggle.addEventListener('pointerdown',e=>e.preventDefault()); // keep iframe focus: no accidental pause
motionToggle.addEventListener('click',()=>{if(!game)return;motionMode=(motionMode+1)%3;game.smooth=motionMode!==2;game.renderer.smoothSprites=motionMode===0?ribbonSprites:originalSprites;motionToggle.textContent=motionLabels[motionMode];motionToggle.setAttribute('aria-pressed',String(game.smooth));game.render();frame.contentWindow.focus();});
function fill(){for(const key of Object.keys(labels))document.querySelector('#cfg-'+key).value=profile[key];document.querySelectorAll('[data-preset]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.preset===profile.id)));}
function archive(reason){if(current){current.telemetry.finish(current,reason);history.push(current.telemetry.text(current));if(history.length>30)history.shift();document.querySelector('#history').replaceChildren(...history.map(v=>{const p=document.createElement('pre');p.textContent=v;return p;}));}}
function install(){game.sessionFactory=options=>{archive(current&&current.telemetry.profile.id!==profile.id?'preset-change':current&&JSON.stringify(current.telemetry.profile)!==JSON.stringify(profile)?'config-change':'restart');current=labSession(profile,options);return current;};}
function start(){if(!game||game.portrait){queued=true;status.textContent=game?'Разверните экран — выбранный preset начнётся в landscape':`Preset ${profile.id} выбран — Training начнётся после загрузки`;return;}queued=false;game.start();frame.contentWindow.focus();status.textContent=`Preset ${profile.id} · новый чистый run · target ${profile.startSpeed.toFixed(2)}, effective ${(60/profileCadence(profile,0)).toFixed(2)} cells/s`+(proofWarning?' · '+proofWarning:'');}
document.querySelectorAll('[data-preset]').forEach(b=>b.addEventListener('click',()=>{profile=PRESETS[b.dataset.preset];fill();start();}));
document.querySelector('#controls').addEventListener('submit',e=>e.preventDefault());
document.querySelector('#apply').addEventListener('click',()=>{try{const p={id:profile.id};for(const key of Object.keys(labels))p[key]=Number(document.querySelector('#cfg-'+key).value);profile=validateProfile(p);start();}catch(e){status.textContent=e.message;}});
function graph(){const canvas=document.querySelector('#speed-graph'),c=canvas.getContext('2d'),samples=current?.telemetry.samples||[];c.clearRect(0,0,640,180);c.font='12px monospace';c.fillStyle='#bfcec4';c.fillText('active seconds → effective cells/s (Focus / Rush included)',10,16);const end=Math.max(60,samples.at(-1)?.time||0),max=12;c.strokeStyle='#345046';for(let n=0;n<=12;n+=3){const y=155-n/max*120;c.beginPath();c.moveTo(32,y);c.lineTo(625,y);c.stroke();c.fillText(String(n),8,y+4);}c.fillText('0',32,174);c.fillText(end.toFixed(0)+'s',580,174);c.strokeStyle='#e1c783';c.beginPath();samples.forEach((s,i)=>{const x=32+s.time/end*585,y=155-s.speed/max*120;i?c.lineTo(x,y):c.moveTo(x,y);});c.stroke();c.fillStyle='#e1c783';for(const s of samples)c.fillRect(31+s.time/end*585,154-s.speed/max*120,3,3);}
function update(){if(game&&queued&&!game.portrait)start();if(!current){graph();return;}const t=current.telemetry,r=t.summary(current),p=t.profile,f=n=>n==null?'—':n.toFixed(2),mult=(1+Math.max(0,current.combo-1)*p.comboStep)*(current.effects.some(e=>e.kind==='harvest')?2:1),speedBonus=1+(profileCadence(p,0)-profileCadence(p,current.tick))*.08;
 document.querySelector('#telemetry').textContent=[`Preset ${p.id} · ${game.status} · ${(current.tick/60).toFixed(1)} active seconds`,`Speed ${f(60/current.cadence())} effective / ${f(targetSpeed(p,current.tick))} target · base max ${p.maxSpeed}`,`Score ${r.score} · length ${r.length} · foods ${r.foods}`,`Combo current ${current.combo} · max ${r.maxCombo} · time avg ${f(r.averageCombo)} · breaks ${r.comboBreaks.length} (${r.comboBreaks.at(-1)?.reason||'none'})`,...(document.querySelector('#show-multiplier').checked?[`Score multiplier ${f(mult*speedBonus)} = combo/Harvest ${f(mult)} × speed ${f(speedBonus)} (pre-rounding)`]:[]),`Food avg ${f(r.averageFoodSeconds)}s / ${f(r.averageFoodDistance)} cells · replacement max ${r.maxReplacementTicks??'—'} ticks / ${r.maxReplacementTicks==null?'—':r.maxReplacementTicks/60}s · invalid ${r.foodFailures}`,`Positive ${r.positivePickups} / spawned ${r.positiveSpawns}; negative ${r.negativePickups} / spawned ${r.negativeSpawns}`,`Portals ${r.portalAppearances} appearances / ${r.portalUses} uses / ${r.portalRejected} rejects · cooldown remaining ${f(r.portalCooldownRemaining)}s`,`Average speed ${f(r.averageSpeed)} · effects ${current.effects.map(e=>e.kind).join(', ')||'none'}`,`Death: ${r.death?JSON.stringify(r.death):'none'}`].join('\n');document.querySelector('#event-log').textContent=t.events.slice(-8).map(e=>`${e.time.toFixed(1)}s ${e.kind}${e.amount?' +'+e.amount:''}${e.reason?' '+e.reason:''}`).join('\n');graph();}
document.querySelector('#copy-results').addEventListener('click',async()=>{if(!current){status.textContent='Сначала начните run';return;}const text=current.telemetry.text(current);try{await navigator.clipboard.writeText(text);status.textContent='Результаты скопированы';}catch{const box=document.querySelector('#copy-fallback');box.hidden=false;box.value=text;box.focus();box.select();status.textContent='Clipboard недоступен — Ctrl+C из выделенного поля';}});
function fit(){const compact=innerHeight<=500&&innerWidth>innerHeight,portrait=innerWidth<=innerHeight;frame.style.height=compact||portrait?innerHeight+'px':Math.ceil(cabinetSize(Math.round(frame.clientWidth*.98),false).h)+'px';}
function resize(){fit();}
fill();resize();window.addEventListener('resize',resize);
const ready=setInterval(()=>{if(frame.contentWindow.forestTraining){clearInterval(ready);game=frame.contentWindow.forestTraining;originalSprites=game.renderer.smoothSprites;ribbonSprites=new RibbonSprites(game.art);game.renderer.smoothSprites=ribbonSprites;install();fit();status.textContent=proofWarning;if(queued)start();}},50);window.addEventListener('pagehide',()=>{clearInterval(ready);if(originalSprites!==game?.renderer.smoothSprites)originalSprites?.release();if(ribbonSprites!==game?.renderer.smoothSprites)ribbonSprites?.release();},{once:true});
const timer=setInterval(update,250);window.addEventListener('pagehide',()=>{clearInterval(timer);game?.dispose();},{once:true});
// Explicit DEV test/debug surface; no bot, autopilot or privileged gameplay path.
window.tuningLab={get profile(){return profile;},get game(){return game;},get current(){return current;},history,summary:()=>current?.telemetry.summary(current),text:()=>current?.telemetry.text(current)};
