import {PRESETS,validateProfile,targetSpeed,profileCadence} from './config.js';
import {ARENAS,designSession} from './arena.js';
import {arenaMeasurements} from './measure.js';
import {cabinetSize} from '../forest-training/renderer.js';
import {EffectRibbonSprites as RibbonSprites} from '../product/appearance/effect-ribbon.js';
import {TunnelSession} from '../gate-one/session.js';
import {installProgression,progressiveEnabled,labConfig} from '../progressive-run/adapter.js';
import {speedTarget as progressiveSpeedTarget} from '../progressive-run/config.js';
import {KINDS} from '../effect-playground/art.js';
import {installArtFixtures} from '../effect-playground/production-fixtures.js';
import {DEFINITIONS} from '../progressive-run/director.js';
import {installTopology} from '../progressive-run/world.js';
import {installVfxReview} from '../effect-playground/behavior-fixtures.js';
import {bodyCell} from '../simulation/body.js';
import {capacity,effectiveRate} from '../effect-playground/capacity-model.js';
import {fitCabinetSize} from '../effect-playground/fit-world.js';
import {build,sourcesMatch,showBuild} from './build-status.js';
const frame=document.querySelector('#training'),status=document.querySelector('#lab-status'),fields=document.querySelector('#fields');
const previews=document.querySelector('#progress-stage');previews.innerHTML=['30×12 · Forest','40×16 · Expansion 1','50×20 · Expansion 2','60×24 · Maximum'].map((v,i)=>`<option value="${i}">${v}</option>`).join('');
document.querySelectorAll('[data-stage]').forEach((b,i)=>{b.dataset.stage=i;b.textContent=['30×12','40×16','50×20','60×24'][i];});
for(const id of ['speed-caps','chapter-thresholds'])document.querySelector('#'+id).parentElement.hidden=true;
document.querySelector('[aria-label="DEV progressive run"] > p').textContent='FIT WORLD V2 · full world, square cells · 15% FREE capacity expansion · fixed-point 60Hz timing. Diagnostic 25%/35% and forced expansion are unranked. STABLE CAMERA remains DEV fallback. No publication.';
const arenaSelect=document.querySelector('#arena-preset'),densitySelect=document.querySelector('#obstacle-density');
const labels={startSpeed:'Start speed · cells/s',maxSpeed:'Max base speed · cells/s',acceleration:'Acceleration · cells/s per second',grace:'Calm start · seconds',foodMin:'Food preferred min · Manhattan cells',foodMax:'Food preferred max · Manhattan cells',positiveInterval:'Positive interval · seconds',negativeInterval:'Negative interval · seconds',portalFirst:'First portal window · seconds',portalInterval:'Portal window interval · seconds',portalWindow:'Portal visible window · seconds',portalCooldown:'Portal cooldown · seconds',comboTimeout:'Combo timeout · seconds',comboStep:'Combo reward step'};
for(const [key,label] of Object.entries(labels)){const l=document.createElement('label');l.textContent=label;const n=document.createElement('input');n.id='cfg-'+key;n.type='number';n.step=['startSpeed','maxSpeed','acceleration','comboStep'].includes(key)?'0.001':'1';l.append(n);fields.append(l);}
let profile=PRESETS.B,game=null,current=null,queued=false,startToken=0,progressAdapter=null,labSessionFactory=null,pendingStart=null;const history=[];
document.querySelector('#run-model').value='progressive';
const motionToggle=document.querySelector('#motion-toggle');
let motionMode=0,originalSprites=null,ribbonSprites=null;
const motionLabels=['SMOOTH V4','SMOOTH V2','GRID SNAP'];
const proofWarning='SMOOTH MOTION V4 = LOCK (fa8c3d1) · Forest gameplay review; no winner selected.';
motionToggle.textContent=motionLabels[motionMode];
motionToggle.addEventListener('pointerdown',e=>e.preventDefault()); // keep iframe focus: no accidental pause
motionToggle.addEventListener('click',()=>{if(!game)return;motionMode=(motionMode+1)%3;game.smooth=motionMode!==2;game.renderer.smoothSprites=motionMode===0?ribbonSprites:originalSprites;motionToggle.textContent=motionLabels[motionMode];motionToggle.setAttribute('aria-pressed',String(game.smooth));game.render();frame.contentWindow.focus();});
function fill(){for(const key of Object.keys(labels))document.querySelector('#cfg-'+key).value=profile[key];document.querySelectorAll('[data-preset]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.preset===profile.id)));}
function resultText(){return current.telemetry.text(current)+'\n'+current.telemetry.designText(current)+(current.world?'\nPROGRESSIVE '+JSON.stringify(current.progressionSummary()):'');}
function archive(reason){if(current){current.telemetry.finish(current,reason);history.push(resultText());if(history.length>30)history.shift();document.querySelector('#history').replaceChildren(...history.map(v=>{const p=document.createElement('pre');p.textContent=v;return p;}));}}
function install(){
 progressAdapter=installProgression(game);
 artFixtures.bind(game);
 labSessionFactory=options=>{archive('restart');exitVfxStress();current=progressiveEnabled()?new TunnelSession({...options,progression:labConfig()}):designSession(profile,{...options,arenaPreset:arenaSelect.value,density:densitySelect.value});current.startsKey=game.starts+1;progressAdapter.reset();return current;};
 game.sessionFactory=labSessionFactory;
 // DEV dimension adaptation only. Do not modify Forest's default sizing or
 // Smooth V4 geometry. All cells/art keep the same uniform 68px-native ratio.
 const render=game.render.bind(game),resize=game.resize.bind(game);
 game.render=()=>{const s=game.session;if(s){const w=Math.round(game.root.getBoundingClientRect().width),size=s.world&&progressAdapter.presentation.cameraMode==='fit'?fitCabinetSize(w,game.compact):cabinetSize(w,game.compact,s.world?28:s.arena.width,s.world?12:s.arena.height);game.root.style.setProperty('--cabinet-height',size.h+'px');const r=game.root.getBoundingClientRect();if(game.renderer.w!==Math.round(r.width)||game.renderer.h!==Math.round(r.height))game.renderer.resize(Math.round(r.width),Math.round(r.height),frame.contentWindow.devicePixelRatio||1);}render();if(game.touch&&s?.arena.height<12){const l=game.renderer.last,pad=game.root.querySelector('#pad');pad.style.top=Math.round(Math.min(parseFloat(pad.style.top),l.arena.y+l.arena.h-92))+'px';}};
 // An iframe resize event can arrive after the new run's synchronous warm-up.
 // Do not invalidate an already-correct board a second time under its clock.
 game.resize=()=>{const r=game.root.getBoundingClientRect(),win=frame.contentWindow;if(game.portrait!==win.matchMedia('(orientation:portrait)').matches||game.compact!==win.matchMedia('(max-height:500px) and (orientation:landscape)').matches||game.renderer.w!==Math.round(r.width)||game.renderer.h!==Math.round(r.height)||game.renderer.dpr!==Math.min(2,win.devicePixelRatio||1))resize();else{game.show();game.render();}};
}
function start(afterStart=null){pendingStart=afterStart;launch();}
function launch(){if(!sourcesMatch){queued=false;frame.dataset.sourceState='stale';status.textContent='STALE DEV MODULES — HARD RELOAD';updateBuild();return;}try{if(progressiveEnabled()){labConfig();profile=PRESETS.B;fill();}}catch(e){status.textContent=e.message;return;}if(!game||game.portrait){queued=true;if(game?.portrait)frame.dataset.sourceState='ready';status.textContent=game?'Разверните экран — выбранный preset начнётся в landscape':`Preset ${profile.id} выбран — Training начнётся после загрузки`;return;}queued=false;game.stop();fit();frame.scrollIntoView({block:'start',behavior:'instant'});const token=++startToken;
 // Finish native select/focus and iframe layout before starting the unchanged
 // fixed clock. Rapid selections coalesce; no old run accrues UI clock debt.
  status.textContent='Preparing clean DEV run…';requestAnimationFrame(()=>requestAnimationFrame(()=>{if(token!==startToken||!frame.isConnected)return;if(game.portrait){queued=true;return;}const afterStart=pendingStart;pendingStart=null;game.start();afterStart?.(game);frame.dataset.sourceState='ready';frame.contentWindow.focus();updateBuild();status.textContent=(current.world?`Balance B · ${current.stage.chapter} · world ${current.world.width}×${current.world.height} · FIT WORLD V2 / STABLE CAMERA · ${(effectiveRate(current)/1e6).toFixed(2)} cells/s · DEV review · `:`Balance ${profile.id} · arena ${arenaSelect.value} ${densitySelect.value} · clean run · ${(60/profileCadence(profile,0)).toFixed(2)} cells/s · `)+proofWarning;frame.scrollIntoView({block:'start',behavior:'instant'});}));}
function startReview(afterStart){
 document.querySelector('#run-model').value='progressive';document.querySelector('#progress-stage').value='0';artFixtures.clearSelection();
 for(const input of document.querySelectorAll('#progress-fields input'))input.value=input.defaultValue;
 document.querySelector('#free-trigger').value='15';document.querySelector('#dev-candidates').checked=true;
 profile=PRESETS.B;motionMode=0;motionToggle.textContent=motionLabels[0];motionToggle.setAttribute('aria-pressed','true');
 if(game){game.sessionFactory=labSessionFactory;game.smooth=true;game.renderer.smoothSprites=ribbonSprites;}
 if(progressAdapter)progressAdapter.presentation.cameraMode='fit';cameraToggle.textContent='FIT WORLD V2';cameraToggle.setAttribute('aria-pressed','true');
 fill();controlsMode();start(afterStart);
}
function implementation(){const s=game?.session;return {model:s?.world?'PROGRESSIVE':s?'STATIC FOREST':game?'MENU':'INITIALIZING',preset:profile.id,world:s?.world?[s.world.width,s.world.height]:null,camera:progressAdapter?.presentation.cameraMode==='fit'?'FIT WORLD V2':'STABLE CAMERA',motion:motionLabels[motionMode],vfx:'VFX B.2',currentFactory:!!game&&game.sessionFactory===labSessionFactory,sourcesMatch};}
function updateBuild(){const s=implementation();showBuild([s.model,s.preset,s.world?.join('×'),s.camera,s.motion,s.vfx].filter(Boolean).join(' · '));}
for(const select of [arenaSelect,densitySelect])select.addEventListener('change',()=>start());
document.querySelector('#run-model').addEventListener('change',()=>{controlsMode();start();});
document.querySelector('#progress-stage').addEventListener('change',()=>start());
document.querySelectorAll('[data-stage]').forEach(b=>b.addEventListener('click',()=>{document.querySelector('#run-model').value='progressive';document.querySelector('#progress-stage').value=b.dataset.stage;controlsMode();start();}));
document.querySelector('#expand-world').addEventListener('pointerdown',e=>e.preventDefault());
document.querySelector('#expand-world').addEventListener('click',()=>{if(current?.world){current.forceExpansion();frame.contentWindow.focus();}else status.textContent='Select progressive run first';});
document.querySelector('#camera-debug').addEventListener('change',()=>game?.render());
const awareness=document.createElement('label');awareness.innerHTML='<input id="world-awareness" type="checkbox" checked> DEV world bounds / viewport / head indicator';document.querySelector('#camera-debug').parentElement.after(awareness);
awareness.querySelector('input').addEventListener('change',()=>game?.render());
// Temporary camera A/B control lives ONLY in the isolated DEV Lab.
const cameraToggle=document.createElement('button');cameraToggle.id='camera-toggle';cameraToggle.textContent='FIT WORLD';cameraToggle.setAttribute('aria-label','FIT WORLD | STABLE CAMERA');cameraToggle.setAttribute('aria-pressed','true');awareness.after(cameraToggle);
cameraToggle.textContent='FIT WORLD V2';cameraToggle.setAttribute('aria-label','FIT WORLD V2 | STABLE CAMERA');
const trigger=document.createElement('label');trigger.innerHTML='FREE TRIGGER <select id="free-trigger"><option value="15">15% · product target</option><option value="25">25% · diagnostic only</option><option value="35">35% · diagnostic only</option></select>';cameraToggle.after(trigger);trigger.querySelector('select').addEventListener('change',start);
const capacityText=document.createElement('pre');capacityText.id='capacity-telemetry';trigger.after(capacityText);
cameraToggle.addEventListener('pointerdown',e=>e.preventDefault());
cameraToggle.addEventListener('click',()=>{if(!progressAdapter)return;const p=progressAdapter.presentation;p.cameraMode=p.cameraMode==='fit'?'stable':'fit';cameraToggle.textContent=p.cameraMode==='fit'?'FIT WORLD V2':'STABLE CAMERA';cameraToggle.setAttribute('aria-pressed',String(p.cameraMode==='fit'));game.render();frame.contentWindow.focus();});
 const playground=document.createElement('section');playground.id='effect-playground';playground.innerHTML='<h2>Effect Playground · DEV only</h2><p>Immediate activation · 2 positive + 1 negative. Use CLEAR EFFECTS between comparisons. <a href="effect-playground/review.html">Locked pickup review</a> · <a href="/docs/qa/effects-production-art-b1/review.html">B.1 actual-scale BEFORE / AFTER review</a> · VFX ART LOCK pending human review.</p><div class="toolbar"></div><p id="effect-playground-status" aria-live="polite"></p>';document.querySelector('[aria-label="DEV progressive run"]').after(playground);
const names=['HARVEST','FOCUS','SPORES','GUARD','PORTAL+','RUSH','CORRUPTION','ROOTS','MIST'];
const artFixtures=installArtFixtures(playground,{getGame:()=>game,start});
function exitVfxStress(){if(game){game.vfxStressStart=null;game.vfxReviewMode=null;}document.querySelectorAll('#vfx-stress,[data-vfx-review]').forEach(b=>b.setAttribute('aria-pressed','false'));}
function clearEffects(){exitVfxStress();if(!current?.world)return;current.effects=[];current.spores=[];current.effectNotices=[];current.pickups=[];current.portalRewardMove=null;current.feedback=[];current.director.warnings=[];current.director.retracts=[];current.director.hazardCooldown=0;current.world.hazards=[];installTopology(current);game.render();}
KINDS.forEach((kind,i)=>{const b=document.createElement('button');b.dataset.effect=kind;b.textContent=names[i];b.addEventListener('pointerdown',e=>e.preventDefault());b.addEventListener('click',()=>{if(!current?.world){status.textContent='Start a progressive DEV run first';return;}
 exitVfxStress();
 // Explicit DEV replacement only; natural collection still enforces 2+1.
 const positive=DEFINITIONS[kind].positive,same=current.effects.filter(e=>DEFINITIONS[e.kind].positive===positive);if(!same.some(e=>e.kind===kind)&&same.length>=(positive?2:1))current.effects=current.effects.filter(e=>e!==same[0]);
 current.collect(kind,bodyCell(current.state,0));if(kind==='portalPrize'){current.director.windowEnd=current.tick+600;current.portal.phase='armed';current.preparePortals();}game.audio.play(positive?'buff':'debuff');document.querySelector('#effect-playground-status').textContent=DEFINITIONS[kind].label+' active · DEV';game.render();frame.contentWindow.focus();});playground.querySelector('.toolbar').append(b);});
const clear=document.createElement('button');clear.textContent='CLEAR EFFECTS';clear.id='clear-effects';clear.addEventListener('pointerdown',e=>e.preventDefault());clear.addEventListener('click',()=>{clearEffects();document.querySelector('#effect-playground-status').textContent='Effects cleared · DEV';frame.contentWindow.focus();});playground.querySelector('.toolbar').append(clear);
installVfxReview(playground,startReview,()=>frame.contentWindow.focus());
const stress=document.createElement('button');stress.id='vfx-stress';stress.textContent='VFX STRESS';stress.setAttribute('aria-pressed','false');stress.addEventListener('pointerdown',e=>e.preventDefault());stress.addEventListener('click',()=>{if(!current?.world)return;if(game.vfxStressStart!=null)exitVfxStress();else{exitVfxStress();game.vfxStressStart=current.tick;stress.setAttribute('aria-pressed','true');}document.querySelector('#effect-playground-status').textContent=game.vfxStressStart==null?'Stress OFF':'DEV render-only stress · synthetic overlap events · canonical gameplay unchanged';game.render();frame.contentWindow.focus();});playground.querySelector('.toolbar').append(stress);
function controlsMode(){const progressive=progressiveEnabled();for(const b of document.querySelectorAll('[data-preset]'))b.disabled=progressive&&b.dataset.preset!=='B';arenaSelect.disabled=densitySelect.disabled=progressive;document.querySelector('[aria-label="DEV Forest design"]').hidden=progressive;for(const n of fields.querySelectorAll('input'))n.disabled=progressive;}
document.querySelectorAll('[data-preset]').forEach(b=>b.addEventListener('click',()=>{profile=PRESETS[b.dataset.preset];fill();start();}));
document.querySelector('#controls').addEventListener('submit',e=>e.preventDefault());
document.querySelector('#apply').addEventListener('click',()=>{try{const p={id:profile.id};for(const key of Object.keys(labels))p[key]=Number(document.querySelector('#cfg-'+key).value);profile=validateProfile(p);start();}catch(e){status.textContent=e.message;}});
function graph(){const canvas=document.querySelector('#speed-graph'),c=canvas.getContext('2d'),samples=current?.telemetry.samples||[];c.clearRect(0,0,640,180);c.font='12px monospace';c.fillStyle='#bfcec4';c.fillText('active seconds → effective cells/s (Focus / Rush included)',10,16);const end=Math.max(60,samples.at(-1)?.time||0),max=12;c.strokeStyle='#345046';for(let n=0;n<=12;n+=3){const y=155-n/max*120;c.beginPath();c.moveTo(32,y);c.lineTo(625,y);c.stroke();c.fillText(String(n),8,y+4);}c.fillText('0',32,174);c.fillText(end.toFixed(0)+'s',580,174);c.strokeStyle='#e1c783';c.beginPath();samples.forEach((s,i)=>{const x=32+s.time/end*585,y=155-s.speed/max*120;i?c.lineTo(x,y):c.moveTo(x,y);});c.stroke();c.fillStyle='#e1c783';for(const s of samples)c.fillRect(31+s.time/end*585,154-s.speed/max*120,3,3);}
function update(){updateBuild();if(game&&queued&&!game.portrait)launch();if(!current){graph();return;}const t=current.telemetry,r=t.summary(current),p=t.profile,f=n=>n==null?'—':n.toFixed(2),mult=(1+Math.max(0,current.combo-1)*p.comboStep)*(current.effects.some(e=>e.kind==='harvest')?2:1),speedBonus=1+(profileCadence(p,0)-(current.world?current.pacing.cadence(current.tick):profileCadence(p,current.tick)))*.08;
 if(current.state.movement){const c=capacity(current);capacityText.textContent=`WORLD ${current.world.width}×${current.world.height} · FREE ${(c.freeRatio*100).toFixed(2)}% (${c.free}/${c.traversableCapacity})\n${current.stage.index===3?'MAX WORLD · NO FURTHER EXPANSION':`NEXT EXPANSION AT ${c.trigger}% · predicted length ${c.predictedExpansionLength}`}\nTarget ${f(effectiveRate(current)/1e6)} cells/s · actual committed average ${f(current.tick?current.moves*60/current.tick:0)} cells/s\nActual expansions: ${current.capacityExpansions.map(e=>`${e.world.join('×')}: predicted ${e.predictedExpansionLength} / actual ${e.actualLength}${e.devForced?' (DEV forced)':''}`).join('; ')||'none'}`;}else capacityText.textContent='';
 const speedLine=current.state.movement?`Speed target ${f(effectiveRate(current)/1e6)} · actual committed average ${f(current.tick?current.moves*60/current.tick:0)} cells/s · fixed-point v1 (historical timing hashes not comparable)`:current.world?`Speed ${f(60/current.cadence())} effective / ${f(progressiveSpeedTarget(current.tick,current.progress,current.config))} target · stage base cap ${current.config.speedCaps[Math.min(4,current.stage.index)]}`:`Speed ${f(60/current.cadence())} effective / ${f(targetSpeed(p,current.tick))} target · base max ${p.maxSpeed}`;
 const biome=current.world?current.stage.multiplier:1,corruption=current.effects.some(e=>e.kind==='weak')?.6:1;
 const multiplierLine=`Score multiplier ${f(mult*speedBonus*biome*corruption)} = combo/Harvest ${f(mult)} × speed ${f(speedBonus)}${current.world?` × biome ${f(biome)} × Corruption ${f(corruption)}`:''} (pre-rounding)`;
 const a=arenaMeasurements(current),spawn=t.foodSpawns.at(-1),quiet=r.quietIntervals,pace=t.pacingSummary(current);
 document.querySelector('#progress-telemetry').textContent=current.world?JSON.stringify({...current.progressionSummary(),camera:progressAdapter.presentation.lastView,activeEffects:current.effects.map(e=>({kind:e.kind,seconds:(e.ends-current.tick)/60,charge:e.charges})),hash:current.hash()},null,2):'Static Forest comparison; progression disabled.';
 document.querySelector('#world-telemetry').textContent=[`Arena ${current.design?.arenaPreset||'B'} · ${a.columns}×${a.rows} logical / ${a.interiorColumns}×${a.interiorRows} interior · ${current.design?.density||'MEDIUM'}`,`Traversable ${a.traversableCells} · vacant now ${a.traversableCells-current.state.length} · run average ${f(r.averageVacantCells)} · stones ${a.stoneCount} (${(100*a.stoneOccupancy).toFixed(1)}%) · pad ${a.padBlocked} cells`,`Mushroom: spawn ${spawn?.distance??'—'} Manhattan / ${spawn?.terrainDistance??'—'} terrain cells · mean ${f(r.averageSpawnDistance)} · food gap ${f(r.averageFoodSeconds)}s · trip ${f(r.averageTripCells)} cells · ${f(r.pickupRatePerMinute)}/min`,`Since last mushroom ${f(pace.sinceLastMushroom)}s · max gap ${f(pace.maxMushroomGap)}s · preference fallbacks ${pace.preferredDistanceFallbacks}`,`Bonus mean spawn distance ${f(r.averageBonusDistance)} · stone approaches ${r.stoneApproaches} · event-quiet gaps >8s ${quiet.length} (${quiet.length?f(Math.max(...quiet.map(q=>q.seconds))):'0'}s max; proxy, not proof of no choice)`].join('\n');
 document.querySelector('#telemetry').textContent=[`Preset ${p.id} · ${game.status} · ${(current.tick/60).toFixed(1)} active seconds`,speedLine,`Score ${r.score} · length ${r.length} · foods ${r.foods}`,`Combo current ${current.combo} · max ${r.maxCombo} · time avg ${f(r.averageCombo)} · breaks ${r.comboBreaks.length} (${r.comboBreaks.at(-1)?.reason||'none'})`,...(document.querySelector('#show-multiplier').checked?[multiplierLine]:[]),`Food avg ${f(r.averageFoodSeconds)}s / ${f(r.averageFoodDistance)} cells · replacement max ${r.maxReplacementTicks??'—'} ticks / ${r.maxReplacementTicks==null?'—':r.maxReplacementTicks/60}s · invalid ${r.foodFailures}`,`Positive ${r.positivePickups} / spawned ${r.positiveSpawns}; negative ${r.negativePickups} / spawned ${r.negativeSpawns}`,`Portals ${r.portalAppearances} appearances / ${r.portalUses} uses / ${r.portalRejected} rejects · cooldown remaining ${f(r.portalCooldownRemaining)}s`,`Average speed ${f(r.averageSpeed)} · effects ${current.effects.map(e=>e.kind).join(', ')||'none'}`,`Death: ${r.death?JSON.stringify(r.death):'none'}`].join('\n');document.querySelector('#event-log').textContent=t.events.slice(-8).map(e=>`${e.time.toFixed(1)}s ${e.kind}${e.amount?' +'+e.amount:''}${e.reason?' '+e.reason:''}`).join('\n');graph();}
document.querySelector('#copy-results').addEventListener('click',async()=>{if(!current){status.textContent='Сначала начните run';return;}const text=resultText();try{await navigator.clipboard.writeText(text);status.textContent='Результаты скопированы';}catch{const box=document.querySelector('#copy-fallback');box.hidden=false;box.value=text;box.focus();box.select();status.textContent='Clipboard недоступен — Ctrl+C из выделенного поля';}});
function fit(){const f=artFixtures.selected;if(f){frame.style.width=f.w+'px';frame.style.height=f.h+'px';return;}frame.style.width='';const compact=innerHeight<=500&&innerWidth>innerHeight,portrait=innerWidth<=innerHeight,p=progressiveEnabled()?ARENAS.B:ARENAS[arenaSelect.value],w=Math.round(frame.clientWidth*.98),badgeHeight=document.querySelector('#dev-build').offsetHeight;frame.style.scrollMarginTop=badgeHeight+'px';frame.style.height=compact?Math.max(1,innerHeight-badgeHeight)+'px':portrait?innerHeight+'px':Math.ceil((progressiveEnabled()?fitCabinetSize(w,false):cabinetSize(w,false,p.width,p.height)).h)+'px';}
function resize(){fit();}
fill();controlsMode();resize();window.addEventListener('resize',resize);
updateBuild();
const ready=setInterval(()=>{if(frame.contentWindow.forestTraining){clearInterval(ready);game=frame.contentWindow.forestTraining;originalSprites=game.renderer.smoothSprites;ribbonSprites=new RibbonSprites(game.art);game.ribbonV4=ribbonSprites;game.renderer.smoothSprites=ribbonSprites;install();fit();status.textContent=proofWarning;launch();}},50);window.addEventListener('pagehide',()=>{clearInterval(ready);if(originalSprites!==game?.renderer.smoothSprites)originalSprites?.release();if(ribbonSprites!==game?.renderer.smoothSprites)ribbonSprites?.release();},{once:true});
const timer=setInterval(update,250);window.addEventListener('pagehide',()=>{clearInterval(timer);game?.dispose();},{once:true});
// Explicit DEV test/debug surface; no bot, autopilot or privileged gameplay path.
window.tuningLab={build,get implementation(){return implementation();},get profile(){return profile;},get game(){return game;},get current(){return current;},get progression(){return current?.world?current.progressionSummary():null;},get camera(){return progressAdapter?.presentation.lastView;},get biomeAudio(){return progressAdapter?.music.summary();},get design(){return {arenaPreset:arenaSelect.value,density:densitySelect.value};},history,summary:()=>current?.telemetry.summary(current),text:()=>current&&resultText(),measurements:()=>current?.world?{...current.progressionSummary(),viewport:[28,12],backing:[current.arena.width,current.arena.height],camera:progressAdapter?.presentation.lastView}:current&&arenaMeasurements(current)};
