import {bodyCell} from '../simulation/body.js';
import {validateFood} from '../simulation/food.js';
import {EFFECTS} from '../forest-training/session.js';
import {manhattan,distances} from './measure.js';

const mean=a=>a.length?a.reduce((s,n)=>s+n,0)/a.length:null;
export function deathCause(s){
 const death=s.state.events.find(e=>e.type==='death'),cell=death?.cell,w=s.arena.width,h=s.arena.height;
 if(s.state.reason==='self')return 'self';
 if(s.state.reason==='obstacle'){if(cell==null)return 'other';const x=cell%w,y=Math.floor(cell/w);return x<=0||x>=w-1||y<=0||y>=h-1?'wall':'obstacle';}
 return 'other';
}
export class Telemetry {
 constructor(profile){this.profile=profile;this.samples=[];this.events=[];this.foodIntervals=[];this.foodDistances=[];this.replacementTicks=[];this.foodFailures=0;this.positiveSpawns=0;this.negativeSpawns=0;this.positive=0;this.negative=0;this.portalAppearances=0;this.portalUses=0;this.portalRejected=0;this.maxCombo=0;this.comboSum=0;this.speedSum=0;this.count=0;this.comboBreaks=[];this.lastFood=null;this.death=null;this.end=null;this.wasVisible=false;this.foodSpawns=[];this.foodTrips=[];this.bonusSpawns=[];this.quietIntervals=[];this.lastEventTick=0;this.vacantSum=0;this.stoneApproaches=0;this.nearStone=false;this.stoneFoodClearance=[];this.stonePickupClearance=[];this.lastTurnTick=0;this.maxStraightSeconds=0;}
 foodSpawn(s,reason){if(s.state.food<0)return;const head=bodyCell(s.state,0),cell=s.state.food,w=s.arena.width,d=distances(s.arena,head),rocks=s.rocks||[],stoneCells=new Set(rocks.map(p=>p.y*w+p.x)),without=distances({...s.arena,blocked:c=>s.arena.blocked(c)&&!stoneCells.has(c)},head);this.currentFood={tick:s.tick,moves:s.moves,cell,reason,distance:manhattan(head,cell,w),terrainDistance:d[cell],stoneDetour:d[cell]-without[cell]};this.foodSpawns.push({...this.currentFood});if(rocks.length)this.stoneFoodClearance.push(Math.min(...rocks.map(p=>manhattan(p.y*w+p.x,cell,w))));}
 observe(s,before){
  if(before.status!=='playing')return;
  this.count++;const speed=60/s.cadence();this.speedSum+=speed;this.comboSum+=s.combo;this.maxCombo=Math.max(this.maxCombo,s.combo);this.vacantSum+=s.arena.freeCount-s.state.length;
  const visible=['entering','teleport','exit-grace'].includes(s.portal.phase)||(s.portal.phase==='armed'&&s.portalAvailable());
  let meaningful=false;if(visible&&!this.wasVisible){this.portalAppearances++;meaningful=true;}this.wasVisible=visible;
  const existing=new Set(before.pickups.map(p=>p.kind+':'+p.cell+':'+p.ends));for(const p of s.pickups)if(!existing.has(p.kind+':'+p.cell+':'+p.ends)){if(EFFECTS[p.kind].positive)this.positiveSpawns++;else this.negativeSpawns++;const w=s.arena.width,head=bodyCell(s.state,0);this.bonusSpawns.push({tick:s.tick,kind:p.kind,distance:manhattan(head,p.cell,w),terrainDistance:distances(s.arena,head)[p.cell]});if(s.rocks.length)this.stonePickupClearance.push(Math.min(...s.rocks.map(r=>manhattan(r.y*w+r.x,p.cell,w))));meaningful=true;}
  for(const e of s.events){
   if(e.kind==='seed'){
    if(this.currentFood)this.foodTrips.push({...this.currentFood,seconds:(e.tick-this.currentFood.tick)/60,cellsTravelled:s.moves-this.currentFood.moves});
    if(this.lastFood){this.foodIntervals.push((e.tick-this.lastFood.tick)/60);this.foodDistances.push(s.moves-this.lastFood.moves);}
    this.lastFood={tick:e.tick,moves:s.moves};
    const valid=s.state.food>=0&&!s.forbidden(s.state.food)&&validateFood(s.state,s.arena,s.state.food);
    if(valid)this.replacementTicks.push(s.tick-e.tick);else this.foodFailures++;
   }
   if(e.kind==='positive')this.positive++;if(e.kind==='negative')this.negative++;
   if(e.kind==='portal-exit')this.portalUses++;if(e.kind==='portal-rejected')this.portalRejected++;
   if(e.kind==='death'){this.death={cause:deathCause(s),speed:60/s.state.cadence,duration:s.tick/60,length:s.state.length,score:s.score,effects:before.effects.map(e=>e.kind),cell:s.state.events.find(e=>e.type==='death')?.cell};this.finish(s,'death');}
   this.events.push({time:e.tick/60,...e});if(this.events.length>100)this.events.shift();
  }
  if(s.state.food!==before.food||s.foods!==before.foods)this.foodSpawn(s,s.foods!==before.foods?'replacement':'relocation');
  if(s.moves!==before.moves){const head=bodyCell(s.state,0),w=s.arena.width,near=s.rocks.some(p=>manhattan(head,p.y*w+p.x,w)===1);if(near&&!this.nearStone){this.stoneApproaches++;meaningful=true;}this.nearStone=near;if(s.state.direction!==before.direction){this.maxStraightSeconds=Math.max(this.maxStraightSeconds,(s.tick-this.lastTurnTick)/60);this.lastTurnTick=s.tick;}}
  if(s.events.length||before.combo>0&&s.combo===0)meaningful=true;
  if(meaningful){const seconds=(s.tick-this.lastEventTick)/60;if(seconds>8)this.quietIntervals.push({from:this.lastEventTick/60,to:s.tick/60,seconds});this.lastEventTick=s.tick;}
  if(before.combo>0&&(s.combo===0||s.status==='dying')){this.comboBreaks.push({time:s.tick/60,reason:s.status==='dying'?'death':'timeout'});}
  if(s.tick%60===0)this.samples.push({time:s.tick/60,speed,score:s.score,combo:s.combo});if(this.samples.length>1800)this.samples.shift();
 }
 finish(s,reason){if(!this.end){if(reason!=='death'&&s.combo>0)this.comboBreaks.push({time:s.tick/60,reason});this.end={reason,time:s.tick/60,score:s.score,length:s.state.length,foods:s.foods};}}
 pacingSummary(s){const times=[0,...this.foodTrips.map(t=>t.tick+t.seconds*60),s.tick],gaps=times.slice(1).map((tick,i)=>({from:times[i]/60,to:tick/60,seconds:(tick-times[i])/60})),replacements=this.foodSpawns.filter(f=>f.reason==='replacement');return {sinceLastMushroom:(s.tick-(this.lastFood?.tick??0))/60,maxMushroomGap:gaps.length?Math.max(...gaps.map(g=>g.seconds)):0,mushroomStalls:gaps.filter(g=>g.seconds>10),averageReplacementDistance:mean(replacements.map(f=>f.distance)),preferredDistanceFallbacks:replacements.filter(f=>f.distance<this.profile.foodMin||f.distance>this.profile.foodMax).length};}
 designText(s){const r=this.summary(s),p=this.pacingSummary(s),f=n=>n==null?'—':n.toFixed(2);return [`DEV arena ${s.design?.arenaPreset||'B'} ${s.arena.width}×${s.arena.height}; stones ${s.design?.density||'MEDIUM'}; touch ${s.touch}`,`Vacant avg ${f(r.averageVacantCells)} (traversable minus Snake only)`,`Food spawn avg ${f(r.averageSpawnDistance)} Manhattan / ${f(r.averageSpawnTerrainDistance)} terrain; replacement ${f(p.averageReplacementDistance)}; fallback ${p.preferredDistanceFallbacks}`,`Food trips ${f(r.averageTripSeconds)}s / ${f(r.averageTripCells)} cells; ${f(r.pickupRatePerMinute)} mushrooms/min; current gap ${f(p.sinceLastMushroom)}s; max ${f(p.maxMushroomGap)}s`,`Bonus spawn avg ${f(r.averageBonusDistance)} cells; stone approaches ${r.stoneApproaches}`,`Event-quiet gaps >8s ${JSON.stringify(r.quietIntervals)} (proxy, not absence of player choice)`].join('\n');}
 summary(s){return {preset:this.profile.id,profile:this.profile,duration:this.end?.time??s.tick/60,score:this.end?.score??s.score,length:this.end?.length??s.state.length,foods:this.end?.foods??s.foods,maxCombo:this.maxCombo,averageCombo:this.count?this.comboSum/this.count:0,comboBreaks:this.comboBreaks,averageSpeed:this.count?this.speedSum/this.count:0,positiveSpawns:this.positiveSpawns,negativeSpawns:this.negativeSpawns,positivePickups:this.positive,negativePickups:this.negative,portalAppearances:this.portalAppearances,portalUses:this.portalUses,portalRejected:this.portalRejected,portalCooldown:this.profile.portalCooldown,portalCooldownRemaining:s.portal.phase==='cooldown'?Math.max(0,this.profile.portalCooldown-s.portal.elapsed/60):0,averageFoodSeconds:mean(this.foodIntervals),averageFoodDistance:mean(this.foodDistances),maxReplacementTicks:this.replacementTicks.length?Math.max(...this.replacementTicks):null,foodFailures:this.foodFailures,death:this.death,end:this.end?.reason??s.status,design:s.design??{arenaPreset:'B',density:'MEDIUM'},averageVacantCells:this.count?this.vacantSum/this.count:s.arena.freeCount-s.state.length,averageSpawnDistance:mean(this.foodSpawns.map(f=>f.distance)),averageSpawnTerrainDistance:mean(this.foodSpawns.map(f=>f.terrainDistance)),averageBonusDistance:mean(this.bonusSpawns.map(f=>f.distance)),averageTripSeconds:mean(this.foodTrips.map(f=>f.seconds)),averageTripCells:mean(this.foodTrips.map(f=>f.cellsTravelled)),pickupRatePerMinute:s.tick?60*s.foods/(s.tick/60):0,quietIntervals:[...this.quietIntervals,...(s.tick-this.lastEventTick>480?[{from:this.lastEventTick/60,to:s.tick/60,seconds:(s.tick-this.lastEventTick)/60,open:true}]:[])],maxStraightSeconds:Math.max(this.maxStraightSeconds,(s.tick-this.lastTurnTick)/60),stoneApproaches:this.stoneApproaches,minimumStoneFoodDistance:this.stoneFoodClearance.length?Math.min(...this.stoneFoodClearance):null,minimumStonePickupDistance:this.stonePickupClearance.length?Math.min(...this.stonePickupClearance):null};}
 text(s){const r=this.summary(s),seconds=Math.floor(r.duration),f=n=>n==null?'—':n.toFixed(2);return [`Preset ${r.preset}`,`Config: ${JSON.stringify(this.profile)}`,`Run: ${String(Math.floor(seconds/60)).padStart(2,'0')}:${String(seconds%60).padStart(2,'0')} (active time)`,`Score: ${r.score}`,`Length: ${r.length}`,`Foods: ${r.foods}`,`Max combo: ${r.maxCombo}; avg ${f(r.averageCombo)}; breaks ${r.comboBreaks.length} (${r.comboBreaks.map(b=>b.reason).join(', ')||'none'})`,`Positive pickups: ${r.positivePickups} / spawned ${r.positiveSpawns}`,`Negative pickups: ${r.negativePickups} / spawned ${r.negativeSpawns}`,`Portals: ${r.portalAppearances} appearances / ${r.portalUses} uses / ${r.portalRejected} unsafe rejects; cooldown ${r.portalCooldown}s`,`Avg speed: ${f(r.averageSpeed)} cells/s`,`Food interval: ${f(r.averageFoodSeconds)}s / ${f(r.averageFoodDistance)} cells; replacement ${r.maxReplacementTicks??'—'} ticks; failures ${r.foodFailures}`,`Death: ${r.death?JSON.stringify(r.death):'none'}`,`End: ${r.end}`].join('\n');}
}
export function attachTelemetry(s,profile){
 const telemetry=new Telemetry(profile),advance=s.advance.bind(s);telemetry.foodSpawn(s,'initial');s.advance=commands=>{const before={status:s.status,combo:s.combo,speed:60/s.cadence(),effects:s.effects.map(e=>({...e})),pickups:s.pickups.map(p=>({...p})),head:bodyCell(s.state,0),food:s.state.food,foods:s.foods,moves:s.moves,direction:s.state.direction};advance(commands);telemetry.observe(s,before);};s.telemetry=telemetry;return s;
}
