import test from 'node:test';
import assert from 'node:assert/strict';
import {ProductController} from './controller.js';
import {createMockBackend} from './backend.js';
function fixture(state='ready',ready=true){const backend=createMockBackend(state),starts=[];const bridge={ready:async()=>{},start:seed=>starts.push(seed),pause(){},resume(){},stop(){},stats:()=>({score:9000,foods:6,length:14,max_combo:3,portal_uses:1,expansions:0,stage:0,world:[30,12],active_ticks:480,final_hash:'abcdef12'})};const gate={ready:()=>ready,request:async()=>ready};const c=new ProductController({backend,bridge,gate,release:'snake-local-v1'});return {c,backend,starts};}
test('main is initial product route; double start spends once and server seed reaches bridge',async()=>{const {c,backend,starts}=fixture();await c.refresh();assert.equal(c.screen,'main');await Promise.all([c.start('ranked'),c.start('ranked')]);assert.equal(backend.calls.filter(x=>x.method==='start').length,1);assert.equal(starts.length,1);assert.equal(starts[0],c.run.seed);assert.equal(c.screen,'playing');});
test('portrait gate spends no attempt; cancel preserves hub and no session',async()=>{const {c,backend,starts}=fixture('ready',false);await c.refresh();await c.start('ranked');assert.equal(c.screen,'mobile-gate');assert.equal(backend.calls.filter(x=>x.method==='start').length,0);assert.equal(starts.length,0);await c.action('gate-cancel');assert.equal(c.screen,'main');assert.equal(c.hub.attempts_remaining,3);});
test('training ignores unavailable hub and has unlimited replay with no ranked calls',async()=>{const {c,backend}=fixture('network-error');await c.refresh();await c.start('training');c.pause();await c.action('restart');assert.equal(c.screen,'confirm-restart');await c.action('confirm');await c.finish(c.bridge.stats());assert.equal(c.screen,'result');assert.equal(c.result.training,true);await c.start('training');assert.equal(backend.calls.filter(x=>['start','finish'].includes(x.method)).length,0);});
test('pause settings back and cancel confirmations preserve run; ranked reset no second debit',async()=>{const {c,backend}=fixture();await c.refresh();await c.start('ranked');const id=c.run.attempt_id,seed=c.run.seed;c.pause();await c.action('settings');await c.action('back');assert.equal(c.screen,'pause');await c.action('restart');await c.action('cancel');assert.equal(c.run.attempt_id,id);assert.equal(c.screen,'pause');await c.action('exit');await c.action('cancel');assert.equal(c.screen,'pause');await c.action('restart');await c.action('confirm');assert.equal(c.run.attempt_id,id);assert.equal(c.run.seed,seed);assert.equal(backend.calls.filter(x=>x.method==='start').length,1);});
test('finish refreshes confirmed hub, stays terminal, duplicate finish returns same result',async()=>{const {c,backend}=fixture();await c.refresh();await c.start('ranked');await Promise.all([c.finish(c.bridge.stats()),c.finish(c.bridge.stats())]);assert.equal(c.screen,'result');assert.equal(c.result.accepted,true);assert.equal(c.result.record,true);assert.equal(c.hub.best_score,9000);assert.equal(backend.calls.filter(x=>x.method==='finish').length,1);await c.action('settings');await c.action('back');assert.equal(c.screen,'result');});
test('sponsor claim is serialized, credit appears before play, normal counters unchanged',async()=>{const {c,backend}=fixture('sponsor-available');await c.refresh();const n=c.hub.attempts_remaining;await Promise.all([c.claim(),c.claim()]);assert.equal(backend.calls.filter(x=>x.method==='claim').length,1);assert.equal(c.hub.sponsor_attempt_credits,1);assert.equal(c.hub.attempts_remaining,n);assert.equal(c.run,null);});
test('failed finish retains immutable submission for retry and never shows accepted',async()=>{const {c,backend}=fixture();await c.refresh();await c.start('ranked');const finish=backend.finish;backend.finish=async()=>({success:false,status:'network'});await c.finish(c.bridge.stats());assert.equal(c.result.accepted,false);assert.equal(c.screen,'result');backend.finish=finish;await c.action('retry-finish');assert.equal(c.result.accepted,true);assert.equal(c.hub.best_score,9000);});
