// V5 scene composition only. Controller remains the owner of all run routing.
const V5='/grib/mushroom-snake-ui-v5/';
const fmt=n=>Number(n||0).toLocaleString('ru-RU');
export function resultScene(c,{button,image,title}){
 const r=c.result,s=r?.stats||{},h=c.hub,score=r?.accepted?r.response.score??s.score:s.score;
 const ranked=h?.success&&h.available!==false&&(h.attempts_remaining>0||h.sponsor_attempt_credits>0),sponsor=h?.sponsor_attempt_available===true;
 const primary=r?.training?button('training','НОВАЯ ТРЕНИРОВКА','play'):r?.accepted?ranked?button('play-again','СЫГРАТЬ СНОВА','play'):sponsor?button('sponsor','ПОПЫТКА ОТ СПОНСОРА','play'):button('training','ТРЕНИРОВКА','play'):button('retry-finish','ПОВТОРИТЬ ОТПРАВКУ','play');
 return `<section class="result-scene ${r?.record?'record':''}" role="region" aria-labelledby="snake-panel-title">${image('result-hero','result-hero')}${title(r?.training?'ТРЕНИРОВКА':r?.record?'ТВОЁ ИМЯ В ЛЕГЕНДАХ ЛЕСА':'ТВОЙ ПУТЬ ЗАВЕРШЁН',r?.training?'ТРЕНИРОВКА ЗАВЕРШЕНА':r?.accepted?r.record?'НОВЫЙ РЕКОРД!':'ИГРА ОКОНЧЕНА':'РЕЗУЛЬТАТ НЕ ОТПРАВЛЕН')}<div class="result-score ${fmt(score).length>8?'score-wide':''}" aria-label="Итоговый счёт">${fmt(score)}</div><div class="primary-stats">${[['food','ГРИБЫ',s.foods??0],['length','ДЛИНА',s.length??8],['combo','КОМБО','×'+(s.max_combo||1)]].map(([key,label,value])=>`<div><small>${label}</small><img src="${V5}stat-${key}.png" width="104" height="168" alt=""><b>${value}</b></div>`).join('')}</div><p class="result-note">${r?.training?'Тренировка · попытки не тратятся':r?.accepted?'Сохранён · Рекорд: '+fmt(h?.best_score):'Не отправлен · повторите отправку'}</p><div class="actions result-actions">${primary}${button('main','ГЛАВНОЕ МЕНЮ')}</div>${r?.accepted?`<div class="result-share">${button('share','ПОДЕЛИТЬСЯ','icon','share')}<span>Поделиться</span></div>`:''}</section>`;
}
