import {formatReset} from './controller.js';
export const EFFECTS=[['harvest','УРОЖАЙ','harvest','Грибы приносят вдвое больше очков.'],['focus','ФОКУС','focus','Спокойнее движение. Комбо временно не гаснет.'],['spores','СПОРЫ','spores','Собирайте светящиеся споры рядом с путём.'],['guard','ЩИТ','guard','Один заряд защищает от столкновения.'],['portalPrize','ПОРТАЛ+','portal-plus','Заряжает проход и награду за портал.'],['rush','СПЕШКА','rush','Скорость растёт. Планируйте повороты раньше.'],['weak','ПОРЧА','corruption','Грибы дают меньше очков.'],['brambles','КОРНИ','roots','Трещины предупреждают о новых препятствиях.'],['mist','ТУМАН','mist','Следите за препятствиями в тумане.']];
export const escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const ART='/grib/mushroom-snake-menu-v1/',LOGO='/grib/mushroom-snake-retro-v5/logo.png';
const UI='/grib/mushroom-snake-ui-v4/';
const CLEAN='/grib/mushroom-snake-ui-v4-1/';
const SYMBOLS='/grib/mushroom-snake-ui-v4-3/icons/';
const PICKUPS='/grib/mushroom-snake-effects-v1/assets/effects/';
const fmt=n=>Number(n||0).toLocaleString('ru-RU');
const IMAGE_SIZE={'snake-hero':[512,262],'result-hero':[512,336],'guide-book':[256,218],'attempt-mushroom':[64,77],'attempt-sponsor':[64,66],'record-trophy':[128,128]};
const icons={'guide-book':'guide','attempt-mushroom':'attempt','attempt-sponsor':'sponsor','icon-sound':'sound-on','icon-sound-off':'sound-off','icon-fullscreen':'fullscreen','icon-exit-fullscreen':'exit-fullscreen'};
const image=(file,cls='',alt='')=>{const key=icons[file]||file.startsWith('icon-')&&file.slice(5),symbol=key&&!['attempt','sponsor'].includes(key);const [width,height]=key?[48,48]:IMAGE_SIZE[file]||[48,48];return `<img class="${cls}${symbol?' ui-symbol':''}" src="${symbol?SYMBOLS+key+'.png':key?(key==='attempt'?CLEAN:UI)+'icons/'+key+'-48.png':['result-hero','snake-hero'].includes(file)?UI+'hero.png':file==='record-trophy'?SYMBOLS+'trophy.png':ART+file+'.png'}" width="${width}" height="${height}" alt="${alt}" draggable="false">`;};
export const panelSkin=(theme='pause')=>`<div class="panel-skin" aria-hidden="true"><span class="skin-wood"></span>${['top','bottom','left','right'].map(p=>`<span class="skin-edge skin-${p}"></span>`).join('')}${['tl','tr','bl','br'].map(p=>`<img class="skin-corner skin-${p}" src="${UI+'panels/'+p+'.png'}" width="48" height="48" alt="">`).join('')}<img class="skin-crest" src="${UI+'ornaments/crest-'+theme+'.png'}" width="128" height="48" alt=""></div>`;
const button=(action,label,kind='wood',icon='')=>`<button class="btn btn-${kind}" data-action="${action}" aria-label="${escape(label)}">${kind==='icon'?'':`<span class="button-skin" aria-hidden="true"><img class="button-cap cap-left" src="${UI+'buttons/'+kind+'-left.png'}" alt=""><span class="button-center"></span><img class="button-cap cap-right" src="${UI+'buttons/'+kind+'-right.png'}" alt=""></span>`}${icon?image('icon-'+icon,'button-icon'):''}<span class="button-label">${label}</span></button>`;
const shortcut=(action,label,icon)=>`<button class="shortcut" data-action="${action}" aria-label="${label}">${image(icon,'shortcut-icon')}<span>${label}</span></button>`;
const title=(small,large)=>`<header class="panel-heading"><p class="eyebrow">${small}</p><h1 id="snake-panel-title">${large}</h1></header>`;
const closeButton=action=>`<button class="btn btn-icon panel-close" data-action="${action}" aria-label="Закрыть">${image('icon-close','button-icon')}</button>`;
const tabs=(items,active)=>`<nav class="tabs" role="tablist">${items.map(([key,label])=>`<button role="tab" data-tab="${key}" aria-selected="${key===active}">${label}</button>`).join('')}</nav>`;
function tokens(h){
 const normal=Math.max(0,Math.min(3,h?.attempts_remaining||0)),used=Math.max(0,Math.min(2,h?.sponsor_attempts_used||0)),credits=h?.sponsor_attempt_credits||0;
 return `<div class="attempt-tray" aria-label="Обычные попытки: ${normal} из 3. Спонсорские получено: ${used} из 2. Зачислено: ${credits}"><div class="normal-tokens"><small><span class="full-label">ОБЫЧНЫЕ </span>ПОПЫТКИ</small><div class="token-line">${[0,1,2].map(i=>`<span class="token ${i<normal?'available':'spent'}">${image('attempt-mushroom')}</span>`).join('')}</div><span class="count">${normal} / 3</span></div><div class="sponsor-tokens"><small><span class="full-label">ОТ </span>СПОНСОРА</small><div class="token-line">${[0,1].map(i=>`<span class="token gift ${i<credits?'credited':i>=used?'claimable':'spent'}">${image('attempt-sponsor')}</span>`).join('')}</div><span class="count">${used} / 2<span class="full-label"> получено${credits?' · Зачислено '+credits:''}</span></span></div></div>`;
}
function plaque(h){const score=fmt(h?.best_score);return `<div class="record-plaque"><div class="record-safe">${image('icon-trophy','plaque-trophy')}<div class="value-box"><small>РЕКОРД</small><strong class="score-value ${score.length>8?'value-wide':''}">${score}</strong></div></div><div class="rank-safe"><img class="rank-medallion ui-symbol" src="${SYMBOLS}medal-1.png" width="64" height="64" alt=""><div class="value-box"><small>МЕСТО</small><strong class="rank-value">${h?.my_rank?'№'+Number(h.my_rank):'—'}</strong></div></div></div>`;}
function mainRanking(h){return `<section class="tournament-preview tournament-board" aria-label="Три лидера сезона">${panelSkin('tournament')}<header><p class="eyebrow">СЕЗОН ЛЕСА</p><h2>ТОП–3</h2></header><ol class="preview-leaders">${(h?.leaderboard||[]).slice(0,3).map(r=>`<li class="${r.is_me?'is-me':''}"><img class="ui-symbol" src="${SYMBOLS}medal-${Number(r.place)||1}.png" width="64" height="64" alt="${Number(r.place)}-е место"><span>${escape(String(r.name||'Игрок').slice(0,40))}</span><b>${fmt(r.score)}</b></li>`).join('')}</ol>${h?.leaderboard?.length?'':'<p class="note">Лес ждёт первого чемпиона.</p>'}<p class="board-own">Ваше место: ${h?.my_rank?'№'+Number(h.my_rank):'—'}<br>Рекорд: ${fmt(h?.best_score)}</p>${button('rating','ОТКРЫТЬ РЕЙТИНГ')}</section>`;}
export function board(h){
 const rows=(h?.leaderboard||[]).slice(0,10),row=r=>{const place=Number(r.place)||0;return `<li class="${r.is_me?'is-me ':''}${place===1?'is-leader ':''}${place<=3?'podium podium-'+place:''}"><span class="place">${place<=3&&place>0?`<img class="leader-badge ui-symbol" width="52" height="52" src="${SYMBOLS}medal-${place}.png" alt="${place}-е место"><span class="medal-number">${place}</span>`:place||'—'}</span><span class="name">${escape(String(r.name||'Игрок').slice(0,40))}</span><b class="score">${fmt(r.score)}</b></li>`;};
 return `<section class="board tournament-board" aria-label="Рейтинг Mushroom Snake"><ol class="leaderboard ranking-podium" aria-label="Три лидера сезона">${rows.slice(0,3).map(row).join('')}</ol><ol class="leaderboard ranking-list" start="4" aria-label="Места с четвёртого по десятое">${rows.slice(3).map(row).join('')}${rows.length?'':'<li class="empty-board">'+image('record-trophy')+'<p>Лес ждёт своего первого чемпиона.</p></li>'}</ol><p class="board-own ranking-summary">Ваше место: ${h?.my_rank?'№'+Number(h.my_rank):'—'} · Рекорд: ${fmt(h?.best_score)}</p></section>`;
}
function pageSkin(){return `<span class="page-skin" aria-hidden="true"><span class="page-paper"></span>${['top','bottom','left','right'].map(s=>`<span class="page-edge page-${s}"></span>`).join('')}${['tl','tr','bl','br'].map(s=>`<img class="page-corner page-${s}" src="${CLEAN}book/${s}.png" width="96" height="96" alt="">`).join('')}</span>`;}
function bookPage(content,cls=''){return `<section class="book-page ${cls}">${pageSkin()}<div class="page-content">${content}</div></section>`;}
function manual(tab){
 if(tab==='basics')return `<div class="manual-book">${bookPage(`<h3>Управление</h3>${image('snake-hero','guide-snake')}<div class="control-illustrations"><img src="${CLEAN}icons/keyboard.png" width="156" height="92" alt="Стрелки и WASD"><img src="${CLEAN}icons/dpad.png" width="92" height="92" alt="На телефоне — D-pad"></div><p class="control-note">Space / Esc — пауза</p>`,'control-page')}${bookPage(`<h3>Расти. Держи путь.</h3><div class="rule-entries">${[['/grib/mushroom-snake-forest-food/food-red.png','Красный гриб','Растит змейку и приносит очки.'],[CLEAN+'icons/medal-rank.png','Береги путь','Стены, камни и своё тело — опасность.'],[PICKUPS+'portal-plus-field.png','Портал','Весь корпус проходит через туннель.'],[UI+'icons/rank-64.png','Лес растёт','При 15% свободного места мир расширяется.']].map(([src,name,copy])=>`<article><img src="${src}" width="64" height="64" alt=""><div><h4>${name}</h4><p>${copy}</p></div></article>`).join('')}</div><p class="control-note">Быстрый сбор усиливает комбо.</p>`,'rules-page')}</div>`;
 const entries=EFFECTS.slice(tab==='bonuses'?0:5,tab==='bonuses'?5:9),split=Math.ceil(entries.length/2),entry=([,name,file,copy])=>`<article class="book-entry"><img src="${PICKUPS+file}-field.png" width="64" height="64" alt=""><div><h3>${name}</h3><p>${copy}</p></div></article>`;
 return `<div class="manual-book">${bookPage(entries.slice(0,split).map(entry).join(''),'effect-page')}${bookPage(entries.slice(split).map(entry).join(''),'effect-page')}</div>`;
}
export function view(c,settings){
 const h=c.hub,ranked=h?.success&&h.available!==false&&(h.attempts_remaining>0||h.sponsor_attempt_credits>0),sponsor=h?.sponsor_attempt_available===true;
 const notice=c.message?`<p class="notice ${c.screen==='error'?'error':''}">${escape(c.message)}</p>`:'';
 if(c.screen==='main'&&!c.startRequest)return `<div class="title-scene"><section class="main-identity"><div class="brand-wrap"><img class="brand" width="480" height="151" src="${LOGO}" alt="MUSHROOM SNAKE"></div><p class="motto">Расти. Рискуй. Забирай первое место.</p>${image('snake-hero','menu-hero')}</section><section class="main-choices"><div class="actions">${ranked?button('play','ИГРАТЬ','play'):sponsor?button('sponsor','ПОПЫТКА ОТ СПОНСОРА','play'):button('no-attempts','ПОПЫТКИ ИСЧЕРПАНЫ','play')}${button('training','ТРЕНИРОВКА')}</div><p class="training-note">Без ограничений</p><div class="control-family"><div class="menu-shortcuts">${shortcut('rules','КАК ИГРАТЬ','guide-book')}${shortcut('rating','РЕЙТИНГ','icon-leaderboard')}${shortcut('settings','НАСТРОЙКИ','icon-settings')}</div><div class="compact-actions">${button('mute',settings.muted?'Звук выключен':'Звук включён','icon',settings.muted?'sound-off':'sound')}${button('fullscreen',c.fullscreenActive?'Выйти из полного экрана':'Полный экран','icon',c.fullscreenActive?'exit-fullscreen':'fullscreen')}${c.hostSwitch?button('other-game','Другая игра','icon','back'):''}</div></div>${notice}</section><div class="main-info">${tokens(h)}${plaque(h)}</div>${mainRanking(h)}</div>`;
 let type=c.screen,content='',actions='',heading='';
 if(c.screen==='loading'||c.screen==='starting'||c.screen==='finishing'){heading=title('MUSHROOM SNAKE',c.screen==='finishing'?'Сохраняем твой путь…':c.screen==='starting'?'Лес открывается…':'Сезон просыпается…');content=image('attempt-mushroom','loading-mushroom')+'<p class="note">Одно мгновение.</p>';}
 else if(c.screen==='main'&&c.startRequest){type='error';heading=title('ЗАПРОС СОХРАНЁН','Старт не подтверждён');content='<p class="notice">Сервер мог уже выделить попытку. Восстановление повторяет тот же запрос без нового списания.</p>';actions=button('retry-start','Восстановить попытку','play')+button('training','Тренировка');}
 else if(c.screen==='no-attempts'){heading=title('ЛЕС ПОДОЖДЁТ','Попытки закончились');content=tokens(h)+`<p class="notice">Обычные попытки восстановятся ${escape(formatReset(h?.next_attempt_at))}.</p><p class="note">Тренировка доступна без ограничений.<br>${sponsor?'Спонсор может подарить ещё одну попытку.':'Спонсорские снова '+escape(formatReset(h?.next_sponsor_attempt_at))}</p>`;actions=(sponsor?button('sponsor','Попытка от спонсора','play'):'')+button('training','Тренировка',sponsor?'wood':'play')+button('main','Главное меню');}
 else if(c.screen==='pause'){heading=title(c.run?.mode==='training'?'ТРЕНИРОВКА':'РЕЙТИНГОВАЯ ПОПЫТКА','ПАУЗА');content='<p class="note">Лес подождёт.</p>';actions=button('resume','ПРОДОЛЖИТЬ','play')+`<div class="pause-secondary">${button('restart','Начать заново')}${button('settings','Настройки')}${button('exit','Главное меню')}</div>`;}
 else if(c.screen.startsWith('confirm-')){const restart=c.screen==='confirm-restart';type='confirmation';heading=title('ТВОЙ ПУТЬ','Начать заново?'.replace('Начать заново?',restart?'Начать заново?':'Выйти в меню?'));content=`<p class="notice">${restart?c.run?.mode==='ranked'?'Эта же рейтинговая попытка начнётся сначала. Текущий счёт не отправится. Новая попытка не списывается.':'Текущая тренировка завершится. Начнётся новая тренировка.':'Текущая игра завершится без отправки результата.'}</p>`;actions=button('confirm',restart?'Начать заново':'Выйти','danger')+button('cancel',restart?'Отмена':'Остаться');}
 else if(c.screen==='rules'){heading=title('ЛЕСНОЙ ПУТЕВОДИТЕЛЬ','КАК ИГРАТЬ');content=tabs([['basics','ОСНОВЫ'],['bonuses','БОНУСЫ'],['hazards','ОПАСНОСТИ']],c.tab||'basics')+manual(c.tab||'basics');actions=button('back','ПОНЯТНО','wood','back');}
 else if(c.screen==='settings'){heading=title('ТВОЙ ЛЕС','НАСТРОЙКИ');const tab=c.tab||'sound';content=tabs([['sound','ЗВУК'],['game','ИГРА']],tab);
  content+=`<div class="settings-stack"><section class="setting-line"><div class="setting-title">${image('icon-sound','setting-icon')}<div><h3>Звук</h3><p>Музыка и звуки леса</p></div>${button('mute',settings.muted?'ВКЛЮЧИТЬ':'БЕЗ ЗВУКА','wood')}</div>${tab==='sound'?`<details class="sound-mix"><summary>Настроить громкость</summary><div class="sound-controls">${Object.entries({master:'Общая громкость',music:'Музыка',sfx:'Эффекты'}).map(([key,name])=>`<div class="settings-row"><label for="volume-${key}">${name}</label><input id="volume-${key}" data-setting="${key}" aria-label="${name}" type="range" min="0" max="1" step=".05" value="${settings[key]}"><output>${Math.round(settings[key]*100)}%</output></div>`).join('')}</div></details>`:''}</section><section class="setting-line"><div class="setting-title">${image('icon-settings','setting-icon')}<div><h3>Визуальные эффекты</h3><p>Предупреждения видны в обоих режимах</p></div>${button('quality',settings.quality==='eco'?'БЕРЕЖНЫЕ':'ЯРКИЕ','wood')}</div></section><section class="setting-line"><div class="setting-title">${image('icon-fullscreen','setting-icon')}<div><h3>Полный экран</h3><p>Весь лес — перед тобой</p></div>${button('fullscreen',c.fullscreenActive?'ВЫЙТИ':'ОТКРЫТЬ','wood')}</div></section></div>`;actions=button('back','ГОТОВО','wood','back');
 }else if(c.screen==='result'){const r=c.result,s=r?.stats||{},score=r?.accepted?r.response.score??s.score:s.score;type='result'+(r?.record?' record':'');heading=title(r?.training?'ТРЕНИРОВКА':r?.record?'ТВОЁ ИМЯ В ЛЕГЕНДАХ ЛЕСА':'ТВОЙ ПУТЬ ЗАВЕРШЁН',r?.training?'Тренировка завершена':r?.accepted?r.record?'НОВЫЙ РЕКОРД!':'Игра окончена':'Результат не отправлен');content=`<div class="result-layout"><div class="result-ornament">${image('result-hero','result-hero')}${r?.record?`<img class="result-trophy" src="${UI}ornaments/trophy.png" width="128" height="128" alt="Рекорд">`:''}<p>${r?.record?'ЛЕС ЗАПОМНИТ ТВОЙ РЕКОРД':r?.training?'НОВЫЙ ПУТЬ — КОГДА ЗАХОЧЕШЬ':'РАСТИ. РИСКУЙ. ВОЗВРАЩАЙСЯ.'}</p></div><div class="result-story"><div class="result-score">${fmt(score)}</div><div class="primary-stats"><div>${image('attempt-mushroom')}<small>ГРИБЫ</small><b>${s.foods??0}</b></div><div>${image('icon-rank')}<small>ДЛИНА</small><b>${s.length??8}</b></div><div>${image('icon-combo')}<small>КОМБО</small><b>×${s.max_combo||1}</b></div></div><details class="result-details"><summary>Порталы ${s.portal_uses??0} · Мир ${(s.world||[30,12]).join('×')} · ${Math.round((s.active_ticks||0)/60)} с</summary><p>Расширения ${s.expansions??0} · Бонусы ${s.bonuses??0}<br>Рекорд сезона: ${fmt(h?.best_score)}</p></details><p class="note">${r?.training?'Попытки не тратились. Результат не попал в рейтинг.':r?.accepted?'Результат сохранён.':'Сохранён для безопасного повтора отправки.'}</p></div></div>`;actions=(r?.training?button('training','НОВАЯ ТРЕНИРОВКА','play'):r?.accepted?ranked?button('play-again','СЫГРАТЬ СНОВА','play'):sponsor?button('sponsor','ПОПЫТКА ОТ СПОНСОРА','play'):button('training','ТРЕНИРОВКА','play'):button('retry-finish','ПОВТОРИТЬ ОТПРАВКУ','play'))+`<div class="result-secondary">${r?.accepted?button('share','ПОДЕЛИТЬСЯ','wood','share'):''}${button('main','ГЛАВНОЕ МЕНЮ')}</div>`;
 }else if(c.screen==='rating'){return `<div class="fantasy-panel panel-rating" data-size="large" role="dialog" aria-label="Рейтинг Mushroom Snake">${panelSkin('tournament')}${closeButton('back')}${title('СЕЗОН ЛЕСА','РЕЙТИНГ')}<div class="panel-body rating-scene">${board(h)}</div><div class="actions">${button('back','НАЗАД','wood','back')}</div></div>`;}
 else if(c.screen==='mobile-gate'){heading=title(c.run?'ТЕКУЩАЯ ПОПЫТКА СОХРАНЕНА':'ПОПЫТКА ЕЩЁ НЕ ТРАТИТСЯ','Разверни свой лес');content=image('snake-hero','gate-hero')+'<p class="notice">Поверните телефон горизонтально. Игра начнётся после перехода в полный экран.</p>'+notice+(c.gateMode==='accepted-start'?'<p class="notice">Сервер уже выделил попытку. Продолжите без нового списания. Выход завершит её без результата.</p>':'');actions=button('gate-confirm','ПОЛНЫЙ ЭКРАН · ПРОДОЛЖИТЬ','play')+button('gate-cancel',c.gateMode==='accepted-start'?'Завершить попытку':c.run?'Оставить на паузе':'Главное меню');}
 else{type='error';heading=title('СВЯЗЬ С ЛЕСОМ','Лес пока недоступен');content=image('attempt-mushroom','error-mushroom')+(notice||'<p class="notice error">Проверьте соединение и обновите сезон.</p>');actions=(c.startRequest?button('retry-start','Восстановить попытку','play'):'')+button('refresh','Обновить сессию',c.startRequest?'wood':'play')+button('training','Тренировка')+button('main','Главное меню');}
 const size=({settings:'medium',rules:'large',result:'result'})[c.screen]||'compact';
 const closeAction=c.screen==='pause'?'resume':c.screen.startsWith('confirm-')?'cancel':['rules','settings'].includes(c.screen)?'back':c.screen==='mobile-gate'?'gate-cancel':'main';
 const close=['loading','starting','finishing'].includes(c.screen)?'':closeButton(closeAction);
 const theme=c.screen.startsWith('confirm-')?'confirm':c.screen==='settings'?'settings':c.screen==='rules'?'guide':c.screen==='result'?'result':'pause';
 return `<div class="fantasy-panel panel-${type}" data-size="${size}" role="dialog" aria-labelledby="snake-panel-title">${panelSkin(theme)}${close}${heading}<div class="panel-body">${content}</div><div class="actions">${actions}</div></div>`;
}
