import {formatReset} from './controller.js';
const base='/grib/mushroom-snake-effects-v1/assets/effects/';
export const EFFECTS=[['harvest','УРОЖАЙ','harvest','Грибы приносят вдвое больше очков.'],['focus','ФОКУС','focus','Спокойнее движение. Комбо временно не гаснет.'],['spores','СПОРЫ','spores','Собирайте светящиеся споры рядом с путём.'],['guard','ЩИТ','guard','Один заряд защищает от столкновения.'],['portalPrize','ПОРТАЛ+','portal-plus','Заряжает проход и награду за портал.'],['rush','СПЕШКА','rush','Скорость растёт. Планируйте повороты раньше.'],['weak','ПОРЧА','corruption','Грибы дают меньше очков.'],['brambles','КОРНИ','roots','Трещины предупреждают о новых препятствиях.'],['mist','ТУМАН','mist','Следите за препятствиями в тумане.']];
const fmt=n=>Number(n||0).toLocaleString('ru-RU');
export const escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const btn=(action,label,primary=false,disabled=false)=>`<button class="btn ${primary?'primary':''}" data-action="${action}" ${disabled?'disabled':''}>${label}</button>`;
const title=(k,h)=>`<div class="menu-title"><p class="eyebrow">${k}</p><h1>${h}</h1></div>`;
export function board(h){return `<section class="board" aria-label="Рейтинг Mushroom Snake"><header><h2>ТОП–10</h2><span class="season">СЕЗОН ЛЕСА</span></header><ol class="leaderboard">${(h?.leaderboard||[]).slice(0,10).map(r=>`<li class="${r.is_me?'is-me':''} ${Number(r.place)===1?'is-leader':''}"><span class="place">${Number(r.place)===1?'<img class="leader-badge" src="/grib/mushroom-fly-v2/ui/icons-recovery-v1/leader-first-v1.png" alt="1-е место">':Number(r.place)||'—'}</span><span class="name">${escape(String(r.name||'Игрок').slice(0,40))}</span><b class="score">${fmt(r.score)}</b></li>`).join('')}</ol>${h?.leaderboard?.length?'':'<p class="note">Рейтинг откроется после первой завершённой игры.</p>'}<p class="board-own">Ваше место: ${h?.my_rank?'№'+Number(h.my_rank):'—'} · Рекорд: ${fmt(h?.best_score)}</p></section>`;}
export function view(c,settings){
 if(c.screen==='main'&&c.startRequest)return `<div class="screen-content">${title('ЗАПРОС СОХРАНЁН','Старт не подтверждён')}<p class="notice">Сервер мог уже выделить попытку. Восстановление повторяет тот же запрос без нового списания.</p><div class="actions">${btn('retry-start','Восстановить попытку',true)}${btn('training','Тренировка')}</div></div>`;
 const h=c.hub,ranked=h?.success&&h.available!==false&&(h.attempts_remaining>0||h.sponsor_attempt_credits>0),sponsor=h?.sponsor_attempt_available===true,notice=c.message?`<p class="notice ${c.screen==='error'?'error':''}">${escape(c.message)}</p>`:'';
 if(c.screen==='main')return `<div class="menu-grid"><section><img class="brand" src="/grib/mushroom-snake-retro-v5/logo.png" alt="MUSHROOM SNAKE"><p class="motto">Расти. Рискуй. Забирай первое место.</p><div class="stats"><div><small>ПОПЫТКИ</small><strong>${h?.attempts_remaining??'—'} / 3</strong></div><div><small>РЕКОРД</small><strong>${fmt(h?.best_score)}</strong></div><div><small>МЕСТО</small><strong>${h?.my_rank?'№'+h.my_rank:'—'}</strong></div></div><p class="attempt-detail">Обычные ${h?.attempts_remaining??0} / 3 · Спонсорские ${h?.sponsor_attempts_used??0} / ${h?.sponsor_attempt_limit??2}${h?.sponsor_attempt_credits?` · Зачислено ${h.sponsor_attempt_credits}`:''}</p>${notice}<div class="actions">${ranked?btn('play','ИГРАТЬ',true):sponsor?btn('sponsor','ПОПЫТКА ОТ СПОНСОРА',true):btn('no-attempts','ПОПЫТКИ ИСЧЕРПАНЫ',true)}${btn('training','ТРЕНИРОВКА')}${btn('rules','КАК ИГРАТЬ?')}${btn('settings','НАСТРОЙКИ')}<span class="menu-mobile-board">${btn('rating','РЕЙТИНГ')}</span></div><div class="compact-actions">${btn('mute',settings.muted?'ЗВУК: ВЫКЛ':'ЗВУК: ВКЛ')}${btn('fullscreen','⛶',false)}${c.hostSwitch?btn('other-game','ДРУГАЯ ИГРА'):''}</div><p class="note">Тренировка без ограничений · Рейтинг: лучший результат одной игры</p></section>${board(h)}</div>`;
 let content='',actions='',heading='';
 if(c.screen==='loading'||c.screen==='starting'||c.screen==='finishing'){heading=title('MUSHROOM SNAKE',c.screen==='finishing'?'Отправляем результат…':c.screen==='starting'?'Готовим лес…':'Загружаем сезон…');content='<p class="note">Одно мгновение.</p>';}
 else if(c.screen==='no-attempts'){heading=title('СЕЗОН ЛЕСА','Попытки закончились');content=`<p class="notice">Обычные попытки восстановятся ${escape(formatReset(h?.next_attempt_at))}.<br>Тренировка доступна без ограничений.</p><p class="note">Спонсорские: ${h?.sponsor_attempts_used??0} / 2 · ${sponsor?'доступна дополнительная попытка':'снова '+escape(formatReset(h?.next_sponsor_attempt_at))}</p>`;actions=(sponsor?btn('sponsor','Попытка от спонсора',true):'')+btn('training','Тренировка',!sponsor)+btn('main','Главное меню');}
 else if(c.screen==='pause'){heading=title(c.run?.mode==='training'?'ТРЕНИРОВКА':'РЕЙТИНГОВАЯ ПОПЫТКА','Пауза');content='<p class="note">Лес подождёт. Продолжите, когда будете готовы.</p>';actions=btn('resume','Продолжить',true)+btn('restart','Начать заново')+btn('settings','Настройки')+btn('exit','Главное меню');}
 else if(c.screen.startsWith('confirm-')){const restart=c.screen==='confirm-restart';heading=title('ПОДТВЕРДИТЕ ДЕЙСТВИЕ',restart?'Начать заново?':'Выйти в меню?');content=`<p class="notice">${restart?c.run?.mode==='ranked'?'Эта же рейтинговая попытка начнётся сначала. Текущий счёт не отправится. Новая попытка не списывается.':'Текущая тренировка завершится. Начнётся новая тренировка.':'Текущая игра завершится без отправки результата.'}</p>`;actions=btn('confirm',restart?'Начать заново':'Выйти',true)+btn('cancel',restart?'Отмена':'Остаться');}
 else if(c.screen==='rules'){heading=title('ПУТЕВОДИТЕЛЬ','Как играть?');const tab=c.tab||'basics';content=tabs([['basics','ОСНОВЫ'],['bonuses','БОНУСЫ'],['hazards','ОПАСНОСТИ']],tab);
  const cards=tab==='basics'?[['Управление','Стрелки / WASD. На телефоне — D-pad. Противоположный поворот запрещён.'],['Красный гриб','Даёт очки и рост. Быстрые сборы усиливают комбо.'],['Столкновение','Стена, камень или собственное тело завершают игру. Щит спасает один раз.'],['Расширение','При 15% свободной вместимости граница открывается и мир растёт.'],['Портал','Войдите в кольцо. Тело последовательно проходит туннель.'],['Пауза','Space / Escape или Ⅱ. Время и эффекты останавливаются.']].map(([n,t])=>`<article><div><b>${n}</b><p>${t}</p></div></article>`):EFFECTS.slice(tab==='bonuses'?0:5,tab==='bonuses'?5:9).map(([,n,file,t])=>`<article><img src="${base+file}-hud.png" alt=""><div><b>${n}</b><p>${t}</p></div></article>`);content+=`<div class="guide">${cards.join('')}</div>`;actions=btn('back','Понятно!',true);
 }else if(c.screen==='settings'){heading=title('НА УСТРОЙСТВЕ','Настройки');const tab=c.tab||'sound';content=tabs([['sound','ЗВУК'],['game','ИГРА']],tab);
  content+=tab==='sound'?Object.entries({music:'Музыка',sfx:'Эффекты',master:'Общая громкость'}).map(([key,name])=>`<div class="settings-row"><label for="volume-${key}">${name}</label><input id="volume-${key}" data-setting="${key}" aria-label="${name}" type="range" min="0" max="1" step=".05" value="${settings[key]}"><output>${Math.round(settings[key]*100)}%</output></div>`).join(''):`<div class="settings-row"><label>Все звуки</label>${btn('mute',settings.muted?'ВКЛЮЧИТЬ':'ВЫКЛЮЧИТЬ')}</div><div class="settings-row"><label>Визуальные эффекты</label>${btn('quality',settings.quality==='eco'?'БЕРЕЖНЫЕ':'ЯРКИЕ')}</div><div class="settings-row"><label>Полный экран</label>${btn('fullscreen','ОТКРЫТЬ')}</div><p class="note">Бережный режим сохраняет предупреждения, порталы и читаемость змейки.</p>`;actions=btn('back','Готово',true);
 }else if(c.screen==='result'){const r=c.result,s=r?.stats||{},score=r?.accepted?r.response.score??s.score:s.score;heading=title(r?.training?'ТРЕНИРОВКА':r?.record?'ЛУЧШИЙ РЕЗУЛЬТАТ СЕЗОНА':'РЕЗУЛЬТАТ ИГРЫ',r?.training?'Тренировка завершена':r?.accepted?r.record?'Новый рекорд!':'Игра окончена':'Результат не отправлен');content=`<p class="eyebrow" style="text-align:center">ИТОГОВЫЙ СЧЁТ</p><p class="result-score">${fmt(score)}</p><div class="result-grid">${[['Грибы',s.foods],['Длина',s.length],['Макс. комбо','×'+(s.max_combo||1)],['Порталы',s.portal_uses],['Расширения',s.expansions],['Время',Math.round((s.active_ticks||0)/60)+' с'],['Бонусы',s.bonuses],['Мир',(s.world||[30,12]).join('×')],['Рекорд сезона',fmt(h?.best_score)]].map(([n,v])=>`<div><small>${n}</small><b>${escape(v??0)}</b></div>`).join('')}</div><p class="note">${r?.training?'Попытки не тратились. Результат не попал в рейтинг.':r?.accepted?'Результат принят '+(c.backend.mode==='mock'?'локальным mock-сервером.':'сервером.'):'Сохранён для безопасного повтора отправки. Новая игра не начинается автоматически.'}</p>`;
  actions=(r?.training?btn('training','Новая тренировка',true):r?.accepted?ranked?btn('play-again','Сыграть снова',true):sponsor?btn('sponsor','Попытка от спонсора',true):btn('training','Тренировка',true):btn('retry-finish','Повторить отправку',true))+btn('main','Главное меню')+(r?.accepted?btn('share','Поделиться'):'');
 }else if(c.screen==='rating'){heading=title('MUSHROOM SNAKE','Рейтинг сезона');content=board(h);actions=btn('back','Назад',true);}
 else if(c.screen==='mobile-gate'){heading=title(c.run?'ТЕКУЩАЯ ПОПЫТКА СОХРАНЕНА':'ПОПЫТКА ЕЩЁ НЕ ТРАТИТСЯ','Полный экран и landscape');content='<img class="gate-art" src="/grib/mushroom-snake-retro-v5/logo.png" alt="Mushroom Snake"><p class="notice">Поверните телефон горизонтально. Игра начнётся после перехода в полный экран.</p>'+notice;if(c.gateMode==='accepted-start')content+='<p class="notice">Сервер уже выделил попытку. Продолжите её без нового списания. Выход завершит эту попытку без результата.</p>';actions=btn('gate-confirm','Полный экран · Продолжить',true)+btn('gate-cancel',c.gateMode==='accepted-start'?'Завершить попытку':c.run?'Оставить на паузе':'Главное меню');}
 else{heading=title('СЕССИЯ И СОЕДИНЕНИЕ','Лес пока недоступен');content=notice||'<p class="notice error">Проверьте соединение и обновите сезон.</p>';actions=(c.startRequest?btn('retry-start','Восстановить начатую попытку',true):'')+btn('refresh','Обновить сессию',!c.startRequest)+btn('training','Тренировка')+btn('main','Главное меню');}
 return `<div class="screen-content">${heading}${content}<div class="actions">${actions}</div></div>`;
}
function tabs(items,active){return `<div class="tabs" role="tablist">${items.map(([key,label])=>`<button role="tab" data-tab="${key}" aria-selected="${key===active}">${label}</button>`).join('')}</div>`;}
