async page=>{
 const browser=page.context().browser(),dir='docs/qa/forest-cabinet-v2/',scratch='.playwright-cli/',base='http://127.0.0.1:8773',url=base+'/arcade/snake-next/forest-training.html?qa=1';
 const errors=[],warnings=[],failed=[],http=[],measurements=[];
 const assert=(ok,message)=>{if(!ok)throw Error(message);};
 const attach=p=>{p.on('pageerror',e=>errors.push(e.message));p.on('console',e=>{if(e.type()==='warning')warnings.push(e.text());});p.on('requestfailed',r=>failed.push(r.url()));p.on('response',r=>{if(r.status()>=400)http.push({url:r.url(),status:r.status()});});};
 const fixture=(p,touch)=>p.evaluate(async touch=>{
  const g=forestTraining;g.touch=touch;g.start();g.stop();g.session=new g.preview.constructor({touch});const s=g.session,{createState}=await import('/arcade/snake-next/entry.js');
  const body=[],push=(x,y)=>body.push(x+y*28);for(let y=8;y>=5;y--)push(7,y);for(let x=8;x<=16;x++)push(x,5);for(let y=4;y>=2;y--)push(16,y);for(let x=17;x<=22;x++)push(x,2);
  s.state=createState({seed:56103,rules:s.rules,arena:s.arena,body:body.reverse(),direction:1,food:79});s.score=12400;s.combo=3;s.tick=1500;s.effects=[{kind:'focus',ends:1812}];s.pickups=[{kind:'focus',cell:117,ends:2700},{kind:'rush',cell:218,ends:2700}];s.portal.phase='armed';g.status='playing';g.show();g.render();
 },touch);
 const measure=async p=>{
  await p.waitForFunction(()=>{const g=forestTraining,r=g.root.getBoundingClientRect();return Math.abs(g.renderer.w-r.width)<1&&Math.abs(g.renderer.h-r.height)<1;});
  return p.evaluate(()=>{
  const g=forestTraining,stage=g.root.getBoundingClientRect(),hud=g.root.querySelector('#hud').getBoundingClientRect(),l=g.renderer.last;
  return {viewport:{w:innerWidth,h:innerHeight},stage:stage.toJSON(),hud:hud.toJSON(),layout:l,outsideBottom:stage.height-l.cabinet.y-l.cabinet.h,body:Array.from(g.session.state.body).slice(0,g.session.state.length),targets:[...g.root.querySelectorAll('#hud button,#pad button')].map(b=>({name:b.ariaLabel,w:b.getBoundingClientRect().width,h:b.getBoundingClientRect().height}))};
 });};
 const ctx=await browser.newContext({viewport:{width:1920,height:1080},deviceScaleFactor:1}),p=await ctx.newPage();attach(p);await p.goto(url);await p.waitForFunction(()=>window.forestTraining);await fixture(p,false);
 let m=await measure(p);measurements.push(m);assert(m.outsideBottom>=-.5&&m.outsideBottom<1,'1920 embedded not shrink-wrapped');
 await p.screenshot({path:scratch+'cabinet-v2-1920.png'});await p.locator('#hud').screenshot({path:dir+'03-hud-native.png'});
 await p.screenshot({path:dir+'04-floor-native.png',clip:{x:Math.ceil(m.stage.x+m.layout.arena.x+m.layout.cell*2),y:Math.ceil(m.layout.arena.y+m.layout.cell*5),width:Math.floor(m.layout.cell*4),height:Math.floor(m.layout.cell*4)}});
 const body=JSON.stringify(m.body),height=m.stage.height;
 await p.evaluate(()=>{document.body.style.display='grid';document.body.style.height='1600px';document.body.style.alignItems='stretch';const n=document.createElement('p');n.id='page-flow';n.textContent='Normal website content below the game';document.body.append(n);});assert(Math.abs((await measure(p)).stage.height-height)<1,'Parent stretched stage');
 assert(await p.evaluate(()=>document.querySelector('#page-flow').getBoundingClientRect().top>=document.querySelector('#game').getBoundingClientRect().bottom),'Website overlaps game');await p.evaluate(()=>{document.body.style.cssText='';document.querySelector('#page-flow').remove();});
 await p.setViewportSize({width:1366,height:768});m=await measure(p);measurements.push(m);assert(m.outsideBottom>=-.5&&m.outsideBottom<1,'1366 embedded blank band');assert(JSON.stringify(m.body)===body,'Resize changed body');await p.screenshot({path:scratch+'cabinet-v2-1366.png'});
 await p.evaluate(()=>{
  const g=forestTraining,l=g.renderer.last,r=g.root.getBoundingClientRect();
  const box=(q,ink,label)=>{const n=document.createElement('div');n.className='qa';Object.assign(n.style,{position:'absolute',pointerEvents:'none',left:q.x+'px',top:q.y+'px',width:q.w+'px',height:q.h+'px',border:'2px solid '+ink,color:ink,font:'12px monospace',zIndex:5});n.textContent=label;g.root.append(n);};
  box({x:0,y:0,w:r.width,h:r.height},'#ffffff','STAGE '+r.width.toFixed(1)+' × '+r.height.toFixed(1));box(l.hud,'#ffe07b','HUD '+l.hud.h.toFixed(1));box(l.arena,'#7cf0d7','ARENA '+l.arena.w.toFixed(1)+' × '+l.arena.h.toFixed(1));
  const n=document.createElement('div');n.className='qa';n.textContent='STAGE ENDS HERE — unused below cabinet '+(r.height-l.cabinet.h).toFixed(2)+' px';Object.assign(n.style,{position:'absolute',bottom:'1px',left:'160px',color:'#fff',font:'12px monospace',zIndex:10});g.root.append(n);
  const below=document.createElement('p');below.id='below';below.textContent=`STAGE ${r.width.toFixed(1)}×${r.height.toFixed(1)} | HUD ${l.hud.w.toFixed(1)}×${l.hud.h.toFixed(1)} | ARENA ${l.arena.w.toFixed(1)}×${l.arena.h.toFixed(1)}\nWEBSITE FLOW starts here — not game letterbox. UNUSED below cabinet: ${(r.height-l.cabinet.h).toFixed(2)} px`;below.style.cssText='white-space:pre-line;margin:12px 24px;color:#a6b8ad;font:14px/1.5 monospace';g.root.after(below);
 });await p.screenshot({path:dir+'06-embedded-geometry.png'});await p.evaluate(()=>{document.querySelectorAll('.qa').forEach(n=>n.remove());document.querySelector('#below').remove();});
 await p.locator('[data-action=fullscreen]').click();await p.waitForFunction(()=>document.fullscreenElement);const full=await measure(p);assert(full.layout.cabinet.y>=0&&full.layout.cabinet.x>=0,'Fullscreen clipping');measurements.push({...full,mode:'fullscreen'});await p.keyboard.press('Escape');await p.waitForFunction(()=>!document.fullscreenElement);assert((await measure(p)).outsideBottom<1,'Fullscreen exit did not shrink-wrap');
 await p.evaluate(()=>forestTraining.main());await p.locator('[data-action=start]').click();await p.waitForFunction(()=>forestTraining.session.state.tick>18);await p.keyboard.press('Space');const paused=await p.evaluate(()=>forestTraining.session.hash());await p.waitForTimeout(100);assert(await p.evaluate(()=>forestTraining.session.hash())===paused,'Paused simulation changed');await p.locator('[data-action=resume]').click();await p.waitForFunction(()=>forestTraining.status==='playing');await p.keyboard.press('Space');await ctx.close();
 const mobile=await browser.newContext({viewport:{width:844,height:390},hasTouch:true,isMobile:true,deviceScaleFactor:1}),q=await mobile.newPage();attach(q);await q.goto(url);await q.waitForFunction(()=>window.forestTraining);await fixture(q,true);m=await measure(q);measurements.push(m);assert(m.targets.every(t=>t.w>=44&&t.h>=44),'Touch target too small');await q.screenshot({path:dir+'05-mobile-844.png'});
 await q.evaluate(()=>{const g=forestTraining;g.session.effects.push({kind:'harvest',ends:1812},{kind:'rush',ends:1812});g.render();});
 const stack=await q.evaluate(()=>{const hud=document.querySelector('#hud').getBoundingClientRect();return [...document.querySelectorAll('#effects .effect span,#effects .effect b')].every(n=>{const r=n.getBoundingClientRect();return r.top>=hud.top&&r.bottom<=hud.bottom;});});assert(stack,'Mobile stack HUD overflow');
 await q.locator('#pad [data-dir="2"]').tap();assert(await q.evaluate(()=>forestTraining.commands.some(c=>c.direction===2)),'D-pad failed');await q.locator('[data-action=pause]').tap();await q.locator('[data-action=resume]').tap();await q.waitForFunction(()=>forestTraining.status==='playing');await q.locator('[data-action=pause]').tap();
 await q.setViewportSize({width:390,height:844});await measure(q);assert(await q.evaluate(()=>forestTraining.portrait&&forestTraining.status==='paused'&&!document.querySelector('#overlay').hidden),'Portrait safety prompt regression');
 assert(await q.evaluate(()=>{const root=document.querySelector('#game').getBoundingClientRect();return [...document.querySelectorAll('#hud .stat,#hud button')].every(n=>{const r=n.getBoundingClientRect();return r.left>=root.left&&r.right<=root.right;});}),'Portrait HUD escaped stage');await mobile.close();
 const comparisons=await browser.newContext({deviceScaleFactor:1}),c=await comparisons.newPage();attach(c);
 for(const [w,h,file] of [[1920,1080,'01-target-after-1920.png'],[1366,768,'02-target-after-1366.png']]){
  await c.setViewportSize({width:w*2+24,height:h+64});await c.goto(base+'/');await c.setContent(`<html><head><link rel="icon" href="data:,"></head><body style="margin:0;background:#051b15;color:#efdeb0;font:16px monospace;display:flex;gap:24px"><section><h3>TARGET — whole reference displayed at ${w}×${h}</h3><img style="width:${w}px;height:${h}px;object-fit:contain" src="${base}/docs/qa/retro-v3/target-desktop.png"></section><section><h3>AFTER — native ${w}×${h}; page continues below cabinet</h3><img src="${base}/.playwright-cli/cabinet-v2-${w}.png"></section></body></html>`);await c.evaluate(()=>Promise.all([...document.images].map(i=>i.decode())));await c.screenshot({path:dir+file});
 }await comparisons.close();
 const result={measurements,stackHudWithinRail:stack,errors,warnings,failed,http};
 const d=await browser.newContext(),downloadPage=await d.newPage();await downloadPage.goto(url);const pending=downloadPage.waitForEvent('download');await downloadPage.evaluate(r=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(r,null,2)],{type:'application/json'}));a.download='measurements.json';a.click();},result);await(await pending).saveAs(dir+'measurements.json');await d.close();
 assert(!errors.length&&!warnings.length&&!failed.length&&!http.length,'Console/network errors');return {viewports:measurements.map(m=>({viewport:m.viewport,stage:m.stage,arena:m.layout.arena,cabinet:m.layout.cabinet,outsideBottom:m.outsideBottom})),stack,errors,warnings,failed,http};
}
