import {CELL,TAPER,makeSweep,fieldAt,radiusAt,material,overlays} from '../smooth-v4-proof/ribbon.js';
import {variant} from '../retro-v5/material.mjs';

/** Allocation-bounded live evaluation of the UNCHANGED V4 field/material.
 * The material's constant-radius interior is piecewise constant between
 * native normal pixel coordinates. Tables are generated by V4 itself, not
 * a second painter. Endpoints always use the exact original material call. */
export class RibbonRaster {
 constructor(sources){
  this.sources=sources;this.data=null;this.mask=null;this.fields=new Map();
  const sweep={frame:{start:0},limit:20};
  this.tables=sources.map(source=>{
   const table=new Uint8ClampedArray(73*CELL*4),set=Array(8).fill(source);
   for(let i=0;i<73;i++)for(let u=0;u<CELL;u++){
    const v=-18+i/2,c=material({d:2+(u+.5)/CELL,v,radius:18},sweep,set),n=(i*CELL+u)*4;
    table.set([...c,255],n);
   }
   return table;
  });
 }
 render(frame,w,h){
  if(!this.data||this.w!==w||this.h!==h){this.w=w;this.h=h;this.data=new Uint8ClampedArray(w*h*4);this.mask=new Uint8Array(w*h);}
  const data=this.data,mask=this.mask;data.fill(0);mask.fill(0);
  const sweep=makeSweep(frame),bins=new Map(),identities=[];
  for(const p of sweep.parts){
   const a=p.kind==='line'?{x0:Math.min(p.a.x,p.b.x),x1:Math.max(p.a.x,p.b.x),y0:Math.min(p.a.y,p.b.y),y1:Math.max(p.a.y,p.b.y)}:{x0:p.cx-p.r,x1:p.cx+p.r,y0:p.cy-p.r,y1:p.cy+p.r};
   for(let by=Math.floor((a.y0-18)/CELL);by<=Math.floor((a.y1+18)/CELL);by++)for(let bx=Math.floor((a.x0-18)/CELL);bx<=Math.floor((a.x1+18)/CELL);bx++){
    if(bx<0||by<0||bx*CELL>=w||by*CELL>=h)continue;
    const key=by*Math.ceil(w/CELL)+bx;if(!bins.has(key))bins.set(key,{bx,by,parts:[]});bins.get(key).parts.push(p);
   }
  }
  for(const {bx,by,parts} of bins.values()){
   const local={...sweep,parts};
   // Only unchanged, constant-radius interior fields are memoized. Neither
   // cap nor taper participates in this cache. Bins never own visible art.
   const interior=parts.every(p=>p.d0>=frame.start&&p.d1<=sweep.limit-TAPER/CELL);
   const ref=Math.floor(Math.min(...parts.map(p=>p.d0)));
   const relative=interior?parts.map(p=>p.kind==='line'?{kind:p.kind,a:{x:p.a.x-bx*CELL,y:p.a.y-by*CELL},b:{x:p.b.x-bx*CELL,y:p.b.y-by*CELL},d0:p.d0-ref,d1:p.d1-ref}:{...p,cx:p.cx-bx*CELL,cy:p.cy-by*CELL,d0:p.d0-ref,d1:p.d1-ref}):null;
   const key=interior?JSON.stringify(relative):null;
   let uv=key?this.fields.get(key):null;
   if(key&&!uv){
    uv=new Float64Array(CELL*CELL*2);uv.fill(NaN);
    for(let y=0;y<CELL;y++)for(let x=0;x<CELL;x++){const q=fieldAt(local,bx*CELL+x+.5,by*CELL+y+.5);if(q){const n=(y*CELL+x)*2;uv[n]=q.d-ref;uv[n+1]=q.v;}}
    if(this.fields.size>=128)this.fields.delete(this.fields.keys().next().value);this.fields.set(key,uv);
   }
   for(let y=by*CELL;y<Math.min(h,(by+1)*CELL);y++)for(let x=bx*CELL;x<Math.min(w,(bx+1)*CELL);x++){
    const index=((y-by*CELL)*CELL+x-bx*CELL)*2;
    const q=uv?(Number.isNaN(uv[index])?null:{d:uv[index]+ref,v:uv[index+1]}):fieldAt(local,x+.5,y+.5);if(!q)continue;
    // Proof stores Float32 fields before filling material: retain that exact
    // conversion, including its pixel-boundary decisions.
    const d=Math.fround(q.d),v=Math.fround(q.v),radius=radiusAt(sweep,d),s=Math.max(0,(d-frame.start)*CELL),n=y*w+x,k=n*4;mask[n]=1;
    if(radius===18&&s>23){
     const id=Math.floor(s/CELL),u=Math.floor(s)%CELL,z=v+18,i=Math.floor(z)*2+(Number.isInteger(z)?0:1);
     identities[id]??=variant(id);const table=this.tables[identities[id]],t=(i*CELL+u)*4;
     data[k]=table[t];data[k+1]=table[t+1];data[k+2]=table[t+2];data[k+3]=255;
    }else{const c=material({d,v,radius},sweep,this.sources);data[k]=c[0];data[k+1]=c[1];data[k+2]=c[2];data[k+3]=255;}
   }
  }
  const {dx,dy}=frame.head,dir=dx===1?0:dy===1?1:dx===-1?2:3;
  for(const p of overlays[dir]){const x=Math.floor(sweep.hx+p.x),y=Math.floor(sweep.hy+p.y),n=y*w+x;if(x>=0&&y>=0&&x<w&&y<h&&mask[n]){const k=n*4;data[k]=p.color[0];data[k+1]=p.color[1];data[k+2]=p.color[2];data[k+3]=255;}}
  return {data,mask,sweep,w,h};
 }
 release(){this.data=this.mask=null;this.sources=[];this.tables=[];this.fields.clear();}
}
