async page=>{
  const errors=[],warnings=[],failures=[],notFound=[],cases=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());if(m.type()==='warning')warnings.push(m.text());});page.on('requestfailed',r=>failures.push(r.url()));page.on('response',r=>{if(r.status()===404)notFound.push(r.url());});
  const act=async name=>page.locator(`[data-screen]:not([hidden]) [data-action=${name}]`).first().click();
  await page.goto('http://127.0.0.1:8771/arcade/snake-next/slice.html?qa=1');await page.waitForFunction(()=>!!window.snakeDev?.qa);await page.evaluate(()=>snakeNext.ready);
  for(const [width,height]of [[360,800],[390,844],[430,932]]){
    await page.setViewportSize({width,height});await page.evaluate(()=>snakeDev.main());await page.screenshot({path:`.playwright-cli/phase3a/mobile-main-${width}.png`});await act('training');await page.screenshot({path:`.playwright-cli/phase3a/mobile-prompt-${width}.png`});
    const fit=await page.evaluate(()=>{const r=document.querySelector('[data-screen=prompt] article').getBoundingClientRect();return{top:r.top,bottom:r.bottom,viewport:innerHeight,timers:snakeDev.summary().resources.timers,coarse:matchMedia('(pointer:coarse)').matches,dpr:devicePixelRatio};});if(fit.timers||fit.top<0||fit.bottom>height+1)throw Error('Portrait safety failed');cases.push({width,height,...fit});await act('main');
  }
  for(const [width,height]of [[844,390],[915,412]]){
    await page.setViewportSize({width,height});await act('training');if(await page.evaluate(()=>snakeDev.ui)!=='prompt')throw Error('Mobile Training bypassed fullscreen');await act('continue-landscape');await page.waitForFunction(()=>snakeDev.ui==='playing'&&!!document.fullscreenElement);
    await page.waitForFunction(()=>snakeDev.state.score>=100);await page.locator('#dpad [data-dir="2"]').tap();await page.locator('#dpad [data-dir="1"]').tap();await page.screenshot({path:`.playwright-cli/phase3a/mobile-landscape-${width}.png`});await page.locator('#pause').tap();const hash=await page.evaluate(()=>snakeDev.summary().hash);await act('settings');await page.keyboard.press('Escape');if(await page.evaluate(()=>snakeDev.ui)!=='settings')throw Error('First fullscreen Escape changed modal');await page.keyboard.press('Escape');if(await page.evaluate(()=>snakeDev.ui)!=='paused')throw Error('Settings Escape resumed session');if(hash!==await page.evaluate(()=>snakeDev.summary().hash))throw Error('Pause mutated simulation');
    await act('resume');if(await page.evaluate(()=>snakeDev.ui)!=='prompt')throw Error('Resume without fullscreen allowed');await act('continue-landscape');await page.waitForFunction(()=>snakeDev.ui==='playing');
    const accepted=await page.evaluate(()=>snakeDev.inputLog.filter(i=>i.sequence>0).length);await page.evaluate(()=>snakeDev.qa.collision('obstacle'));await page.waitForFunction(()=>snakeDev.ui==='result');await page.screenshot({path:`.playwright-cli/phase3a/mobile-result-${width}.png`});await act('main');if(await page.evaluate(()=>!!document.fullscreenElement))await page.locator('[data-action=fullscreen]').click();
    await page.waitForFunction(()=>snakeNext.mixer.sources.size===0,{timeout:1500});const resources=await page.evaluate(()=>snakeDev.summary().resources);if(resources.raf||resources.timers||resources.audio||resources.listeners||resources.observers)throw Error('Mobile Main leaked session resources');cases.push({width,height,accepted,resources});
  }
  await page.setViewportSize({width:844,height:390});await act('training');await act('continue-landscape');await page.setViewportSize({width:390,height:844});await page.waitForFunction(()=>['paused','prompt'].includes(snakeDev.ui));const orientation=await page.evaluate(()=>snakeDev.summary());await act('main');if(await page.evaluate(()=>!!document.fullscreenElement))await page.locator('[data-action=fullscreen]').click();
  const result={cases,orientation,errors,warnings,failures,notFound};await page.evaluate(result=>window.phase3aMobile=result,result);return result;
}
