const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict');
const project=process.env.RYTNI_SOURCE_ROOT||'C:/Codex/Rytni Gift/RYTNI_TRANSFER_2026-07-31/CORE/Сайт';
const {chromium}=require(path.join(project,'node_modules/playwright-core'));
const repo=path.resolve(__dirname,'..'),out=path.join(project,'artifacts/arcade-snake');fs.mkdirSync(out,{recursive:true});
const live=process.argv.includes('--live');
const fly=fs.readFileSync(path.join(project,'02_Tilda_7_блоков/08_T123_BROWSER_ARCADE_2.15.34.html'),'utf8');
const snake=fs.readFileSync(path.join(__dirname,'09_T123_ARCADE_HUB_SNAKE.html'),'utf8');
const html='<!doctype html><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><style>body{margin:0;background:#0d1412}#applicationPopup{max-width:1160px;margin:20px auto}</style><div id="applicationPopup"><div id="rytniProgressionHub"><div id="progressionPanelArcade"><div id="rytniArcadeHost"></div></div></div></div>'+fly+snake;
const server=http.createServer((q,r)=>{r.setHeader('Content-Type','text/html;charset=utf-8');r.end(html);});
async function showHost(page){await page.evaluate(()=>{applicationToolMode='boost';window.renderApplicationProfile({id:'preview',user_id:'preview-user',email_linked:true,name:'Rytni_Player',participant_number:7,steamid:'111111111',region:'Беларусь',tiktok:'@rytni.tv/live',games:'Deltarune',level:11,points:7575,correct_streak:6,boost_count:41,daily_chest_count:72,daily_chest_streak:5,best_daily_chest_streak:12,can_daily_chest:true,can_sponsor_chest:true,sponsor_chest_enabled:true,sponsor_chest_reward:150,can_boost:true,test_mode:true});showPopup('applicationPopup');RytniProgressionTabs.refresh();});await page.locator('[data-progression-tab="arcade"]').click();await page.waitForFunction(()=>document.querySelector('[data-progression-tab="arcade"]').getAttribute('aria-selected')==='true');}
async function open(page){await page.goto(live?'https://rytni.live/testpodari?progression_preview=1&ttq_preview=1&arcade_preview=1&mf_perf=1&snake_qa='+Date.now():'http://127.0.0.1:8823/?arcade_preview=1&mf_perf=1',{waitUntil:'domcontentloaded'});await page.waitForFunction(()=>window.MushroomSnakeQA&&document.getElementById('msHub'));if(live){await page.locator('#rytni-app-loader').waitFor({state:'hidden'});await showHost(page);}await page.locator('#msHub').waitFor({state:'visible'});}
const action=(p,a)=>a==='hub'?p.locator('[data-ms-action="hub"]').filter({visible:true}).last():p.locator('[data-ms-action="'+a+'"]').filter({visible:true}).first();
async function shot(p,n){await p.evaluate(async()=>{await new Promise(requestAnimationFrame);const id=RytniArcadeHub.selected==='snake'?'msStage':RytniArcadeHub.selected==='fly'?'msFlyWrap':'msHub';document.getElementById(id).scrollIntoView({block:'start'});await Promise.all(document.getAnimations().filter(a=>Number.isFinite(a.effect?.getTiming().iterations)).map(a=>a.finished.catch(()=>{})));await new Promise(requestAnimationFrame);});await p.screenshot({path:path.join(out,(live?'live-':'local-')+n+'.png')});}
async function main(){if(!live)await new Promise(r=>server.listen(8823,'127.0.0.1',r));const browser=await chromium.launch({executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',headless:true});const report={live,errors:[],http:[],failed:[],modes:[]};try{
for(const mobile of (process.argv.includes('--mobile-only')?[true]:[false,true])){const page=await browser.newPage({viewport:mobile?{width:390,height:844}:{width:1366,height:900},deviceScaleFactor:mobile?3:1,isMobile:mobile,hasTouch:mobile});page.on('pageerror',e=>report.errors.push(e.message));page.on('response',r=>{if(r.status()>=400)report.http.push(r.status()+' '+r.url());});page.on('requestfailed',r=>report.failed.push(r.url()+' '+r.failure()?.errorText));
if(!live)await page.route('https://rytni.github.io/rytni-assets/**',r=>{const suffix=decodeURIComponent(new URL(r.request().url()).pathname.split('/rytni-assets/')[1]),file=path.resolve(repo,suffix);if(!file.startsWith(repo)||!fs.existsSync(file))return r.abort();return r.fulfill({body:fs.readFileSync(file),contentType:file.endsWith('.wav')?'audio/wav':file.endsWith('.ogg')?'audio/ogg':file.endsWith('.webp')?'image/webp':'image/png',headers:{'access-control-allow-origin':'*'}});});
await open(page);await page.locator('.ms-card-art').first().evaluate(i=>i.decode());await shot(page,mobile?'mobile-hub':'desktop-hub');
await action(page,'game-fly').click();await page.locator('#arcadeStart').waitFor({state:'visible'});assert.equal(await page.locator('#arcadeDialog').getAttribute('data-menu'),'main');await shot(page,mobile?'mobile-fly':'desktop-fly');await action(page,'hub').click();assert.equal(await page.evaluate(()=>RytniBrowserArcade.qaRuntime().running),false);
await action(page,'game-snake').click();await page.evaluate(()=>MushroomSnakeQA.state.preload());await shot(page,mobile?'mobile-menu':'desktop-menu');
const mechanics=await page.evaluate(()=>{const E=MushroomSnakeQA.engine,e=new E(42),results={};e.food.forEach(f=>f.cool=100);let f=e.food[0];f.cool=0;f.x=e.x+2;f.y=e.y;e.tick(1/60);results.food=e.foodCount===1&&e.length===11&&e.points===20;f.cool=0;f.x=e.x+2;e.tick(1/60);results.combo=e.combo===2&&e.points===45;const m=e.food[23];m.cool=0;m.x=e.x;m.y=e.y;e.tick(1/60);results.magnet=e.magnet===7&&e.bonuses===1;f.cool=0;f.x=e.x+100;f.y=e.y;const bad=e.food[24];bad.cool=0;bad.x=e.x+110;bad.y=e.y;const old=f.x,oldBad=bad.x;e.tick(1/60);results.magnetSelective=f.x<old&&bad.x===oldBad;bad.x=e.x;bad.y=e.y;e.tick(1/60);results.drunk=e.drunk===4;
const w=new E(7);w.x=1180;w.tick(1/60);results.world=!w.alive&&w.reason==='Лесная граница';const s=new E(8);s.trailX.fill(s.x);s.trailY.fill(s.y);s.tick(1/60);results.self=!s.alive&&s.reason==='Собственный хвост';const h=new E(9);h.hazards[0]={x:h.x+2,y:h.y,r:28,active:true,warn:1};h.tick(1/60);results.warningSafe=h.alive;h.hazards[0].warn=0;h.tick(1/60);results.hazard=!h.alive;
const run=()=>{const x=new E(100);x.food.forEach(f=>f.cool=999);x.hazardClock=999;for(let n=0;n<600;n++){x.target=Math.atan2(337.5-x.y,600-x.x)+Math.PI/2;x.tick(1/60);}return [x.x,x.y,x.scoreNow(),x.alive];};results.deterministic=JSON.stringify(run())===JSON.stringify(run());const curve=new E(4);curve.time=10000;curve.tick(1/60);results.speedCap=curve.speed<=145&&curve.speed>140;return results;});assert(Object.values(mechanics).every(Boolean),JSON.stringify(mechanics));
await action(page,'start').click();if(mobile){await page.waitForFunction(()=>MushroomSnakeQA.state.state==='rotate');assert(!(await page.evaluate(()=>MushroomSnakeQA.snapshot().raf)));await action(page,'enter').click();await page.setViewportSize({width:873,height:393});}await page.waitForFunction(()=>MushroomSnakeQA.state.state==='play');await page.waitForTimeout(350);await shot(page,mobile?'mobile-game':'desktop-game');
const bounds=await page.evaluate(()=>{const s=MushroomSnakeQA.state,v=s.view;return {left:v.x,right:v.x+1200*v.scale,width:v.w,top:v.y,bottom:v.y+675*v.scale,height:v.h,dpr:v.dpr};});assert(bounds.left>=-.01&&bounds.right<=bounds.width+.01&&bounds.top>=-.01&&bounds.bottom<=bounds.height+.01,JSON.stringify(bounds));assert(bounds.dpr<= (mobile?1.5:2));
await action(page,'pause').click();await page.waitForFunction(()=>MushroomSnakeQA.state.state==='pause');const frozen=await page.evaluate(()=>MushroomSnakeQA.state.engine.time);await page.waitForTimeout(150);assert.equal(await page.evaluate(()=>MushroomSnakeQA.state.engine.time),frozen);await shot(page,mobile?'mobile-pause':'desktop-pause');await action(page,'resume').click();await page.waitForFunction(()=>MushroomSnakeQA.state.state==='play');
if(mobile){await page.setViewportSize({width:393,height:873});await page.waitForFunction(()=>MushroomSnakeQA.state.state==='pause');await page.setViewportSize({width:873,height:393});await action(page,'resume').click();await page.waitForFunction(()=>MushroomSnakeQA.state.state==='play');}else{await action(page,'fullscreen').click();await page.waitForTimeout(150);await shot(page,'desktop-fullscreen');await page.evaluate(()=>document.exitFullscreen());}
// Verify actual input events, then let world collision produce Result.
if(mobile){const input=await page.context().newCDPSession(page),box=await page.locator('#msCanvas').boundingBox();await input.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:box.x+200,y:box.y+100}]});await input.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:box.x+200,y:box.y+150}]});assert(Math.abs(await page.evaluate(()=>MushroomSnakeQA.state.engine.target)-Math.PI/2)<.01);await input.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});}else{await page.keyboard.down('ArrowDown');await page.waitForTimeout(50);assert(Math.abs(await page.evaluate(()=>MushroomSnakeQA.state.engine.target)-Math.PI/2)<.01);await page.keyboard.up('ArrowDown');const box=await page.locator('#msCanvas').boundingBox();await page.mouse.move(box.x+box.width-50,box.y+50);assert((await page.evaluate(()=>MushroomSnakeQA.state.engine.target))<0);}
await page.evaluate(()=>MushroomSnakeQA.state.engine.target=0);await page.waitForFunction(()=>MushroomSnakeQA.state.state==='result',null,{timeout:18000});await shot(page,mobile?'mobile-result':'desktop-result');assert(!(await page.evaluate(()=>MushroomSnakeQA.snapshot().raf)));await action(page,'start').click();await page.waitForFunction(()=>MushroomSnakeQA.state.state==='play');
// Long pool / CPU baseline: deterministic safe orbit, all body segments rendered.
const cdp=await page.context().newCDPSession(page);if(mobile)await cdp.send('Emulation.setCPUThrottlingRate',{rate:4});const perf=await page.evaluate(async()=>{const s=MushroomSnakeQA.state;s.pause();const e=s.engine;e.reset(17);e.length=110;e.food.forEach(f=>f.cool=999);e.hazardClock=999;let cpu=[];for(let i=0;i<120;i++){await new Promise(requestAnimationFrame);const t=performance.now();e.target=Math.atan2(337.5-e.y,600-e.x)+Math.PI/2;e.tick(1/60);s.paint();cpu.push(performance.now()-t);}cpu.sort((a,b)=>a-b);return {segments:e.length,p50:cpu[60],p95:cpu[114],dpr:s.view.dpr};});if(mobile)await cdp.send('Emulation.setCPUThrottlingRate',{rate:1});
await action(page,'hub').click();await page.waitForFunction(()=>!MushroomSnakeQA.snapshot().active);let stop=await page.evaluate(()=>MushroomSnakeQA.snapshot());assert(!stop.raf&&!stop.audio.active&&stop.audio.sources===0);
for(let i=0;i<8;i++){await action(page,'game-snake').click();await action(page,'start').click();if(mobile){await action(page,'enter').click();}await page.waitForFunction(()=>MushroomSnakeQA.state.state==='play');if(live){await page.evaluate(()=>{if(document.fullscreenElement)return document.exitFullscreen();document.getElementById('msStage').classList.remove('ms-full');});await page.locator('#applicationPopup .application-room-close').click();}else await page.evaluate(()=>document.getElementById('applicationPopup').hidden=true);await page.waitForFunction(()=>!MushroomSnakeQA.snapshot().active);stop=await page.evaluate(()=>MushroomSnakeQA.snapshot());assert(!stop.raf&&!stop.audio.active&&stop.audio.sources===0);if(live)await showHost(page);else await page.evaluate(()=>{let n=document.getElementById('rytniProgressionHub');while(n&&n!==document.body){n.hidden=false;if(getComputedStyle(n).display==='none')n.style.display='block';n=n.parentElement;}});}
await page.reload({waitUntil:'domcontentloaded'});await page.waitForFunction(()=>window.RytniArcadeHub);assert.equal(await page.evaluate(()=>RytniArcadeHub.selected),null);report.modes.push({mobile,mechanics,bounds,perf,stop});await page.close();}
// The live page uses a client-only preview profile, not a signed-in Supabase session.
// Existing account-only read probes may return 401; assets and all other failures remain fatal.
report.expectedAuthErrors=report.http.filter(s=>/^401 https:\/\/ltqnskxlqsddxdyazbss\.supabase\.co\/(auth\/v1\/health|rest\/v1\/rpc\/(get_my_top10_status|get_giveaway_tiktok_hub_v21516))$/.test(s));
fs.writeFileSync(path.join(out,(live?'live':'local')+'-results.json'),JSON.stringify(report,null,2));
assert.deepEqual(report.errors,[]);assert.deepEqual(report.http.filter(s=>!report.expectedAuthErrors.includes(s)),[]);assert.deepEqual(report.failed.filter(s=>!s.endsWith('net::ERR_ABORTED')),[]);console.log(JSON.stringify(report,null,2));}finally{await browser.close();server.close();}}
main().catch(e=>{console.error(e);process.exitCode=1;server.close();});
